In [1]:
import pandas as pd
import os

raw_path = "Raw_Data"

files = os.listdir(raw_path)

for file in files:
    if file.lower().endswith(".csv"):
        df = pd.read_csv(os.path.join(raw_path, file))
        print(f"{file}  -->  {df.shape}")

billing.csv  -->  (115313, 9)
cities.csv  -->  (68, 8)
complaints.csv  -->  (16584, 7)
contracts.csv  -->  (10607, 9)
customers.csv  -->  (19076, 25)
customer_feedback.csv  -->  (28499, 7)
data_quality_issue_log.csv  -->  (20, 3)
devices.csv  -->  (19000, 8)
employees.csv  -->  (800, 9)
marketing_campaigns.csv  -->  (40, 9)
network_quality.csv  -->  (57000, 8)
payments.csv  -->  (92362, 7)
plans.csv  -->  (25, 10)
plan_history.csv  -->  (19349, 6)
recharges.csv  -->  (146501, 6)
regions.csv  -->  (4, 3)
retention_campaigns.csv  -->  (6475, 8)
states.csv  -->  (36, 4)
stores.csv  -->  (2180, 7)
subscriptions.csv  -->  (20523, 8)
support_tickets.csv  -->  (31490, 11)
usage_data.csv  -->  (57000, 5)
usage_sms.csv  -->  (57000, 5)
usage_voice.csv  -->  (57000, 6)


In [2]:
import pandas as pd
import os

raw_path = "Raw_Data"

files_to_check = [
    "customers.csv",
    "subscriptions.csv",
    "contracts.csv",
    "plans.csv",
    "plan_history.csv"
]

for file in files_to_check:
    df = pd.read_csv(os.path.join(raw_path, file))

    print("\n" + "=" * 70)
    print(file)
    print("=" * 70)
    print("Columns:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)


customers.csv
Columns:
['customer_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'age', 'email', 'phone_number', 'address', 'city_id', 'city_name', 'state_id', 'pin_code', 'city_tier', 'region_id', 'occupation', 'annual_income_inr', 'customer_segment', 'product_line', 'plan_id', 'acquisition_channel', 'acquisition_date', 'tenure_months', 'customer_status', 'churn_date']

Data types:
customer_id                str
first_name                 str
last_name                  str
gender                     str
date_of_birth              str
age                      int64
email                      str
phone_number             int64
address                    str
city_id                    str
city_name                  str
state_id                   str
pin_code                 int64
city_tier                  str
region_id                  str
occupation                 str
annual_income_inr      float64
customer_segment           str
product_line               str
plan_id     

In [3]:
files_to_check = [
    "billing.csv",
    "payments.csv",
    "recharges.csv",
    "usage_data.csv",
    "usage_voice.csv",
    "usage_sms.csv",
    "devices.csv"
]

for file in files_to_check:
    df = pd.read_csv(os.path.join(raw_path, file))

    print("\n" + "=" * 70)
    print(file)
    print("=" * 70)
    print("Columns:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)


billing.csv
Columns:
['invoice_id', 'customer_id', 'billing_date', 'billing_period_month', 'base_amount_inr', 'gst_amount_inr', 'total_amount_inr', 'due_date', 'payment_status']

Data types:
invoice_id                  str
customer_id                 str
billing_date                str
billing_period_month        str
base_amount_inr         float64
gst_amount_inr          float64
total_amount_inr        float64
due_date                    str
payment_status              str
dtype: object

payments.csv
Columns:
['payment_id', 'invoice_id', 'customer_id', 'payment_date', 'amount_inr', 'payment_method', 'payment_status']

Data types:
payment_id            str
invoice_id            str
customer_id           str
payment_date          str
amount_inr        float64
payment_method        str
payment_status        str
dtype: object

recharges.csv
Columns:
['recharge_id', 'customer_id', 'recharge_date', 'amount_inr', 'plan_id', 'payment_method']

Data types:
recharge_id           str
customer_i

In [4]:
files_to_check = [
    "complaints.csv",
    "customer_feedback.csv",
    "support_tickets.csv",
    "network_quality.csv",
    "retention_campaigns.csv"
]

for file in files_to_check:
    df = pd.read_csv(os.path.join(raw_path, file))

    print("\n" + "=" * 70)
    print(file)
    print("=" * 70)
    print("Columns:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)


complaints.csv
Columns:
['complaint_id', 'customer_id', 'complaint_date', 'complaint_type', 'severity', 'status', 'resolution_date']

Data types:
complaint_id       str
customer_id        str
complaint_date     str
complaint_type     str
severity           str
status             str
resolution_date    str
dtype: object

customer_feedback.csv
Columns:
['feedback_id', 'customer_id', 'feedback_date', 'csat_score', 'nps_score', 'channel', 'feedback_category']

Data types:
feedback_id            str
customer_id            str
feedback_date          str
csat_score           int64
nps_score            int64
channel                str
feedback_category      str
dtype: object

support_tickets.csv
Columns:
['ticket_id', 'customer_id', 'created_date', 'category', 'priority', 'channel', 'status', 'first_contact_resolution', 'assigned_employee_id', 'resolution_hours', 'resolution_date']

Data types:
ticket_id                       str
customer_id                     str
created_date               

# NexaTel Data Model Mapping

## Objective

Map the 24 NexaTel tables, identify the central customer table, primary keys,
foreign keys, and major business relationships before beginning data cleaning.

## Central Table

customers.csv

Primary Key:
- customer_id

The customers table is the central entity connecting customer-level,
subscription, billing, usage, service, network, feedback, and retention data.

## Major Data Domains

### 1. Customer & Subscription
- customers
- subscriptions
- plans
- plan_history
- contracts
- devices

### 2. Billing & Payments
- billing
- payments
- recharges

### 3. Customer Usage
- usage_voice
- usage_sms
- usage_data

### 4. Network
- network_quality

### 5. Customer Service
- support_tickets
- complaints
- customer_feedback
- employees

### 6. Retention & Marketing
- retention_campaigns
- marketing_campaigns

### 7. Geography & Operations
- cities
- states
- regions
- stores

### 8. Data Quality
- data_quality_issue_log

## Key Relationship

customers.customer_id
    ↓
Customer-related transactional and service tables

The customer_id field will be the main customer-level link used
for churn analysis.

## Next Step

Validate the detailed primary-key and foreign-key relationships
using the NexaTel ERD and Data Dictionary before beginning
Phase 1 data cleaning.

Step 1 — Load all CSV tables

In [5]:
import pandas as pd
import os

raw_data_path = "raw_data"

tables = {}

for file in os.listdir(raw_data_path):
    if file.lower().endswith(".csv"):
        file_path = os.path.join(raw_data_path, file)
        table_name = os.path.splitext(file)[0]

        df = pd.read_csv(file_path)
        tables[table_name] = df

        print(f"{table_name}: {df.shape[0]} rows, {df.shape[1]} columns")

print("\nTotal CSV tables loaded:", len(tables))

billing: 115313 rows, 9 columns
cities: 68 rows, 8 columns
complaints: 16584 rows, 7 columns
contracts: 10607 rows, 9 columns
customers: 19076 rows, 25 columns
customer_feedback: 28499 rows, 7 columns
data_quality_issue_log: 20 rows, 3 columns
devices: 19000 rows, 8 columns
employees: 800 rows, 9 columns
marketing_campaigns: 40 rows, 9 columns
network_quality: 57000 rows, 8 columns
payments: 92362 rows, 7 columns
plans: 25 rows, 10 columns
plan_history: 19349 rows, 6 columns
recharges: 146501 rows, 6 columns
regions: 4 rows, 3 columns
retention_campaigns: 6475 rows, 8 columns
states: 36 rows, 4 columns
stores: 2180 rows, 7 columns
subscriptions: 20523 rows, 8 columns
support_tickets: 31490 rows, 11 columns
usage_data: 57000 rows, 5 columns
usage_sms: 57000 rows, 5 columns
usage_voice: 57000 rows, 6 columns

Total CSV tables loaded: 24


In [6]:
# ================================================================
# BASIC PROFILING — ALL 24 TABLES
# ================================================================

print("=" * 80)
print("BASIC DATA PROFILING — ALL TABLES")
print("=" * 80)

for table_name, df in tables.items():
    print(f"\n{'=' * 80}")
    print(f"TABLE: {table_name}")
    print(f"{'=' * 80}")

    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")

    print("\nColumns and Data Types:")
    print(df.dtypes.to_string())

    print(f"\nMissing Values: {df.isnull().sum().sum():,}")

BASIC DATA PROFILING — ALL TABLES

TABLE: billing
Rows    : 115,313
Columns : 9

Columns and Data Types:
invoice_id                  str
customer_id                 str
billing_date                str
billing_period_month        str
base_amount_inr         float64
gst_amount_inr          float64
total_amount_inr        float64
due_date                    str
payment_status              str

Missing Values: 0

TABLE: cities
Rows    : 68
Columns : 8

Columns and Data Types:
city_id         str
city_name       str
state_id        str
state_name      str
zone            str
region_id       str
tier            str
pin_prefix    int64

Missing Values: 0

TABLE: complaints
Rows    : 16,584
Columns : 7

Columns and Data Types:
complaint_id       str
customer_id        str
complaint_date     str
complaint_type     str
severity           str
status             str
resolution_date    str

Missing Values: 7,348

TABLE: contracts
Rows    : 10,607
Columns : 9

Columns and Data Types:
contract_id    

------------------------------------------
## Basic Profiling — All Tables

Basic profiling was completed for all 24 source tables. The profiling covered row counts, column counts, column names, data types, and total missing values for each table.

This confirms that all source tables were systematically reviewed before proceeding with detailed data-quality validations and analysis.

**Status: COMPLETED**
-------------------------------------------------

In [7]:
import os

print(os.getcwd())
print(os.listdir("raw_data"))

C:\Users\Abcom\OneDrive\Desktop\Nexatel_Customer_Churn_Analysis
['.ipynb_checkpoints', 'billing.csv', 'cities.csv', 'complaints.csv', 'contracts.csv', 'customers.csv', 'customer_feedback.csv', 'data_quality_issue_log.csv', 'devices.csv', 'employees.csv', 'marketing_campaigns.csv', 'network_quality.csv', 'payments.csv', 'plans.csv', 'plan_history.csv', 'recharges.csv', 'regions.csv', 'retention_campaigns.csv', 'states.csv', 'stores.csv', 'subscriptions.csv', 'support_tickets.csv', 'usage_data.csv', 'usage_sms.csv', 'usage_voice.csv']


Step 2 — Find the columns that can connect the tables

In [8]:
# NexaTel - Column Mapping

for table_name, df in tables.items():
    print("\n" + "=" * 70)
    print(table_name)
    print("=" * 70)
    print(list(df.columns))


billing
['invoice_id', 'customer_id', 'billing_date', 'billing_period_month', 'base_amount_inr', 'gst_amount_inr', 'total_amount_inr', 'due_date', 'payment_status']

cities
['city_id', 'city_name', 'state_id', 'state_name', 'zone', 'region_id', 'tier', 'pin_prefix']

complaints
['complaint_id', 'customer_id', 'complaint_date', 'complaint_type', 'severity', 'status', 'resolution_date']

contracts
['contract_id', 'customer_id', 'plan_id', 'contract_type', 'contract_length_months', 'start_date', 'end_date', 'auto_renew', 'renewal_status']

customers
['customer_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'age', 'email', 'phone_number', 'address', 'city_id', 'city_name', 'state_id', 'pin_code', 'city_tier', 'region_id', 'occupation', 'annual_income_inr', 'customer_segment', 'product_line', 'plan_id', 'acquisition_channel', 'acquisition_date', 'tenure_months', 'customer_status', 'churn_date']

customer_feedback
['feedback_id', 'customer_id', 'feedback_date', 'csat_score', 'np


# Step 3 — NexaTel Table Relationship Mapping

## Central Customer Table

`customers` is the central customer dimension.

Most customer-level tables connect through `customer_id`.

## Customer Relationships

- `customers.customer_id` → `billing.customer_id`
- `customers.customer_id` → `complaints.customer_id`
- `customers.customer_id` → `customer_feedback.customer_id`
- `customers.customer_id` → `devices.customer_id`
- `customers.customer_id` → `contracts.customer_id`
- `customers.customer_id` → `network_quality.customer_id`
- `customers.customer_id` → `payments.customer_id`
- `customers.customer_id` → `plan_history.customer_id`
- `customers.customer_id` → `recharges.customer_id`
- `customers.customer_id` → `retention_campaigns.customer_id`
- `customers.customer_id` → `subscriptions.customer_id`
- `customers.customer_id` → `support_tickets.customer_id`
- `customers.customer_id` → `usage_data.customer_id`
- `customers.customer_id` → `usage_sms.customer_id`
- `customers.customer_id` → `usage_voice.customer_id`

## Plan Relationships

- `customers.plan_id` → `plans.plan_id`
- `subscriptions.plan_id` → `plans.plan_id`
- `contracts.plan_id` → `plans.plan_id`
- `recharges.plan_id` → `plans.plan_id`
- `plan_history.old_plan_id` → `plans.plan_id`
- `plan_history.new_plan_id` → `plans.plan_id`

## Billing & Payment

- `billing.invoice_id` → `payments.invoice_id`

## Geography

- `customers.city_id` → `cities.city_id`
- `cities.state_id` → `states.state_id`
- `customers.region_id` → `regions.region_id`
- `cities.region_id` → `regions.region_id`

## Store & Employee

- `stores.store_id` → `employees.store_id`
- `employees.employee_id` → `support_tickets.assigned_employee_id`

## Validation Required

Before creating the Power BI model, primary-key uniqueness and foreign-key validity must be verified using Python.

Step 4 — Automatically check primary-key uniqueness and foreign-key validity using Python.(Validate the 22 straightforward key candidates)

In [9]:
# Step 4A — Primary Key Uniqueness Check

primary_keys = {
    "billing": "invoice_id",
    "cities": "city_id",
    "complaints": "complaint_id",
    "contracts": "contract_id",
    "customers": "customer_id",
    "customer_feedback": "feedback_id",
    "devices": "device_id",
    "employees": "employee_id",
    "marketing_campaigns": "campaign_id",
    "network_quality": "record_id",
    "payments": "payment_id",
    "plans": "plan_id",
    "plan_history": "history_id",
    "recharges": "recharge_id",
    "regions": "region_id",
    "states": "state_id",
    "stores": "store_id",
    "subscriptions": "subscription_id",
    "support_tickets": "ticket_id",
    "usage_data": "usage_id",
    "usage_sms": "usage_id",
    "usage_voice": "usage_id"
}

print("PRIMARY KEY UNIQUENESS CHECK")
print("=" * 80)

for table, key in primary_keys.items():
    df = tables[table]

    total_rows = len(df)
    unique_values = df[key].nunique()
    null_values = df[key].isna().sum()
    duplicate_values = df[key].duplicated().sum()

    print(
        f"{table:25} | "
        f"Rows: {total_rows:7} | "
        f"Unique: {unique_values:7} | "
        f"Nulls: {null_values:5} | "
        f"Duplicates: {duplicate_values:5}"

    )

PRIMARY KEY UNIQUENESS CHECK
billing                   | Rows:  115313 | Unique:  114969 | Nulls:     0 | Duplicates:   344
cities                    | Rows:      68 | Unique:      68 | Nulls:     0 | Duplicates:     0
complaints                | Rows:   16584 | Unique:   16584 | Nulls:     0 | Duplicates:     0
contracts                 | Rows:   10607 | Unique:   10607 | Nulls:     0 | Duplicates:     0
customers                 | Rows:   19076 | Unique:   19000 | Nulls:     0 | Duplicates:    76
customer_feedback         | Rows:   28499 | Unique:   28499 | Nulls:     0 | Duplicates:     0
devices                   | Rows:   19000 | Unique:   19000 | Nulls:     0 | Duplicates:     0
employees                 | Rows:     800 | Unique:     800 | Nulls:     0 | Duplicates:     0
marketing_campaigns       | Rows:      40 | Unique:      40 | Nulls:     0 | Duplicates:     0
network_quality           | Rows:   57000 | Unique:   57000 | Nulls:     0 | Duplicates:     0
payments             

In [10]:
# Step 4A.1 — Investigate duplicate customer IDs

customers_df = tables["customers"]

duplicate_customers = customers_df[
    customers_df["customer_id"].duplicated(keep=False)
].sort_values("customer_id")

print("Duplicate customer records:")
print(duplicate_customers[["customer_id", "first_name", "last_name",
                           "plan_id", "customer_status", "acquisition_date",
                           "churn_date"]].to_string(index=False))

print("\nNumber of duplicate customer IDs:",
      duplicate_customers["customer_id"].nunique())

Duplicate customer records:
customer_id first_name    last_name plan_id customer_status acquisition_date churn_date
   C0000098      Ayaan       Sheikh   PL013          Active       04-02-2021        NaN
   C0000098      Ayaan       Sheikh   PL013          Active       04-02-2021        NaN
   C0000169       Yash       Shinde   PL003          Active       08-11-2020        NaN
   C0000169       Yash       Shinde   PL003          Active       08-11-2020        NaN
   C0000784       Sita      Hussain   PL002          Active       27-09-2018        NaN
   C0000784       Sita      Hussain   PL002          Active       27-09-2018        NaN
   C0001392      Rohan      Pradhan   PL013          Active       20-08-2024        NaN
   C0001392      Rohan      Pradhan   PL013          Active       20-08-2024        NaN
   C0001394     Preeti        Pawar   PL007          Active       17-02-2022        NaN
   C0001394     Preeti        Pawar   PL007          Active       17-02-2022        NaN
   C

# Step 4A — Primary Key Validation Findings

The primary-key validation was compared with the `data_quality_issue_log`.

The following duplicate records matched exactly:

| Table | Python Validation | Data Quality Log | Result |
|---|---:|---:|---|
| customers | 76 duplicate customer IDs | 76 duplicate customers | Match |
| billing | 344 duplicate invoice IDs | 344 duplicate invoices | Match |
| payments | 276 duplicate payment IDs | 276 duplicate payments | Match |

This confirms that the Python validation is correctly identifying known duplicate-key issues.

Additional data-quality issues are documented in `data_quality_issue_log` and will be investigated during the data-cleaning phase.

Step 4B — Foreign Key Validation

In [11]:
# Step 4B —  Foreign Key Validation

foreign_keys = [
    ("billing", "customer_id", "customers", "customer_id"),
    ("complaints", "customer_id", "customers", "customer_id"),
    ("contracts", "customer_id", "customers", "customer_id"),
    ("customer_feedback", "customer_id", "customers", "customer_id"),
    ("devices", "customer_id", "customers", "customer_id"),
    ("network_quality", "customer_id", "customers", "customer_id"),
    ("payments", "customer_id", "customers", "customer_id"),
    ("payments", "invoice_id", "billing", "invoice_id"),
    ("plan_history", "customer_id", "customers", "customer_id"),
    ("recharges", "customer_id", "customers", "customer_id"),
    ("subscriptions", "customer_id", "customers", "customer_id"),
    ("support_tickets", "customer_id", "customers", "customer_id"),
    ("usage_data", "customer_id", "customers", "customer_id"),
    ("usage_sms", "customer_id", "customers", "customer_id"),
    ("usage_voice", "customer_id", "customers", "customer_id"),

    ("cities", "state_id", "states", "state_id"),
    ("cities", "region_id", "regions", "region_id"),

    ("stores", "city_id", "cities", "city_id"),
    ("stores", "state_id", "states", "state_id"),
    ("stores", "region_id", "regions", "region_id"),

    ("employees", "store_id", "stores", "store_id"),
    ("employees", "region_id", "regions", "region_id"),

    ("support_tickets", "assigned_employee_id", "employees", "employee_id"),

    ("customers", "city_id", "cities", "city_id"),
    ("customers", "region_id", "regions", "region_id"),
    ("customers", "plan_id", "plans", "plan_id"),

    ("contracts", "plan_id", "plans", "plan_id"),
    ("subscriptions", "plan_id", "plans", "plan_id"),
    ("recharges", "plan_id", "plans", "plan_id")
]

print("FOREIGN KEY VALIDATION")
print("=" * 100)

for child_table, child_col, parent_table, parent_col in foreign_keys:

    child_df = tables[child_table]
    parent_df = tables[parent_table]

    parent_values = set(
        parent_df[parent_col].dropna().astype(str)
    )

    child_values = child_df[child_col].dropna().astype(str)

    invalid_count = (~child_values.isin(parent_values)).sum()
    null_count = child_df[child_col].isna().sum()

    print(
        f"{child_table:22}."
        f"{child_col:25} -> "
        f"{parent_table:22}."
        f"{parent_col:15} | "
        f"Invalid: {invalid_count:5} | "
        f"Nulls: {null_count:5}"
    )

FOREIGN KEY VALIDATION
billing               .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
complaints            .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
contracts             .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
customer_feedback     .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
devices               .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
network_quality       .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
payments              .customer_id               -> customers             .customer_id     | Invalid:     0 | Nulls:     0
payments              .invoice_id                -> billing               .invoice_id      | Invalid:   184 | Nulls:

In [12]:
# Step 4C — Validate Remaining Keys and Relationships

print("REMAINING KEY & RELATIONSHIP VALIDATION")
print("=" * 90)

# 1. Plan history → Plans
print("\n1. PLAN HISTORY → PLANS")

plans = set(tables["plans"]["plan_id"].dropna().astype(str))

for column in ["old_plan_id", "new_plan_id"]:
    values = tables["plan_history"][column].dropna().astype(str)
    invalid = (~values.isin(plans)).sum()
    nulls = tables["plan_history"][column].isna().sum()

    print(
        f"plan_history.{column:12} -> plans.plan_id"
        f" | Invalid: {invalid:5} | Nulls: {nulls:5}"
    )


# 2. Retention campaigns → Customers
print("\n2. RETENTION CAMPAIGNS → CUSTOMERS")

customers = set(tables["customers"]["customer_id"].dropna().astype(str))

retention_customers = tables["retention_campaigns"]["customer_id"].dropna().astype(str)

invalid = (~retention_customers.isin(customers)).sum()
nulls = tables["retention_campaigns"]["customer_id"].isna().sum()

print(
    f"retention_campaigns.customer_id -> customers.customer_id"
    f" | Invalid: {invalid:5} | Nulls: {nulls:5}"
)


# 3. Retention campaign IDs
print("\n3. RETENTION CAMPAIGN ID CHECK")

retention = tables["retention_campaigns"]

print("Rows:", len(retention))
print("Unique campaign_id:", retention["campaign_id"].nunique())
print("Duplicate campaign_id values:", retention["campaign_id"].duplicated().sum())

# Check whether campaign_id + customer_id is unique
composite_duplicates = retention.duplicated(
    subset=["campaign_id", "customer_id"]
).sum()

print(
    "Duplicate campaign_id + customer_id combinations:",
    composite_duplicates
)


# 4. Billing invoice IDs
print("\n4. BILLING INVOICE ID CHECK")

billing = tables["billing"]

print("Rows:", len(billing))
print("Unique invoice_id:", billing["invoice_id"].nunique())
print("Duplicate invoice_id values:", billing["invoice_id"].duplicated().sum())


# 5. Payments payment IDs
print("\n5. PAYMENT ID CHECK")

payments = tables["payments"]

print("Rows:", len(payments))
print("Unique payment_id:", payments["payment_id"].nunique())
print("Duplicate payment_id values:", payments["payment_id"].duplicated().sum())


# 6. Check whether duplicate billing rows are exact duplicates
print("\n6. EXACT DUPLICATE BILLING ROWS")

billing_exact_duplicates = billing.duplicated().sum()

print("Exact duplicate billing rows:", billing_exact_duplicates)


# 7. Check whether duplicate payment rows are exact duplicates
print("\n7. EXACT DUPLICATE PAYMENT ROWS")

payment_exact_duplicates = payments.duplicated().sum()

print("Exact duplicate payment rows:", payment_exact_duplicates)

REMAINING KEY & RELATIONSHIP VALIDATION

1. PLAN HISTORY → PLANS
plan_history.old_plan_id  -> plans.plan_id | Invalid:     0 | Nulls:     0
plan_history.new_plan_id  -> plans.plan_id | Invalid:     0 | Nulls:     0

2. RETENTION CAMPAIGNS → CUSTOMERS
retention_campaigns.customer_id -> customers.customer_id | Invalid:     0 | Nulls:     0

3. RETENTION CAMPAIGN ID CHECK
Rows: 6475
Unique campaign_id: 6475
Duplicate campaign_id values: 0
Duplicate campaign_id + customer_id combinations: 0

4. BILLING INVOICE ID CHECK
Rows: 115313
Unique invoice_id: 114969
Duplicate invoice_id values: 344

5. PAYMENT ID CHECK
Rows: 92362
Unique payment_id: 92086
Duplicate payment_id values: 276

6. EXACT DUPLICATE BILLING ROWS
Exact duplicate billing rows: 344

7. EXACT DUPLICATE PAYMENT ROWS
Exact duplicate payment rows: 276


# Step 5 — Final NexaTel Relationship Mapping

Based on the primary-key and foreign-key validation, the following relationships have been identified for the NexaTel Customer Churn Analytics data model.

## 1. Customer Relationships

The `customers` table is the central customer dimension.

| Parent Table | Parent Key | Child Table | Foreign Key |
|---|---|---|---|
| customers | customer_id | billing | customer_id |
| customers | customer_id | complaints | customer_id |
| customers | customer_id | contracts | customer_id |
| customers | customer_id | customer_feedback | customer_id |
| customers | customer_id | devices | customer_id |
| customers | customer_id | network_quality | customer_id |
| customers | customer_id | payments | customer_id |
| customers | customer_id | plan_history | customer_id |
| customers | customer_id | recharges | customer_id |
| customers | customer_id | retention_campaigns | customer_id |
| customers | customer_id | subscriptions | customer_id |
| customers | customer_id | support_tickets | customer_id |
| customers | customer_id | usage_data | customer_id |
| customers | customer_id | usage_sms | customer_id |
| customers | customer_id | usage_voice | customer_id |

## 2. Plan Relationships

| Parent Table | Parent Key | Child Table | Foreign Key |
|---|---|---|---|
| plans | plan_id | customers | plan_id |
| plans | plan_id | contracts | plan_id |
| plans | plan_id | subscriptions | plan_id |
| plans | plan_id | recharges | plan_id |
| plans | plan_id | plan_history | old_plan_id |
| plans | plan_id | plan_history | new_plan_id |

Both `old_plan_id` and `new_plan_id` were validated against `plans.plan_id`.

## 3. Billing and Payments

| Parent Table | Parent Key | Child Table | Foreign Key |
|---|---|---|---|
| billing | invoice_id | payments | invoice_id |

The relationship contains 184 invalid payment invoice references, matching the `data_quality_issue_log`.

## 4. Geography Relationships

| Parent Table | Parent Key | Child Table | Foreign Key |
|---|---|---|---|
| states | state_id | cities | state_id |
| regions | region_id | cities | region_id |
| cities | city_id | stores | city_id |
| states | state_id | stores | state_id |
| regions | region_id | stores | region_id |
| cities | city_id | customers | city_id |
| regions | region_id | customers | region_id |

## 5. Employee and Store Relationships

| Parent Table | Parent Key | Child Table | Foreign Key |
|---|---|---|---|
| stores | store_id | employees | store_id |
| regions | region_id | employees | region_id |
| employees | employee_id | support_tickets | assigned_employee_id |

## 6. Data Quality Table

`data_quality_issue_log` is treated as a data-quality reference table rather than a business relationship table.

It documents known issues identified in the NexaTel source data.

## 7. Important Data Quality Findings

- `customers`: 76 exact duplicate records
- `billing`: 344 exact duplicate invoice records
- `payments`: 276 exact duplicate payment records
- `payments.invoice_id`: 184 invalid foreign-key references
- `subscriptions.plan_id`: 41 null foreign keys

These issues will be handled during the data-cleaning stage. The original raw CSV files will remain unchanged.

## Objective

The validated relationships above will be used as the foundation for designing the NexaTel data model before implementation in Power BI.

# Step 5B — Fact and Dimension Classification

The NexaTel tables are initially classified based on their business purpose and row-level grain.

## Dimension / Reference Tables

- `customers` — customer master information
- `plans` — telecom plan master information
- `cities` — city/location reference
- `states` — state reference
- `regions` — regional reference
- `stores` — store master information
- `employees` — employee master information
- `marketing_campaigns` — marketing campaign information

## Fact / Activity Tables

- `billing` — invoice-level transactions
- `payments` — payment-level transactions
- `subscriptions` — customer subscription records
- `contracts` — customer contract records
- `plan_history` — customer plan changes
- `recharges` — recharge transactions
- `usage_data` — monthly data usage
- `usage_sms` — monthly SMS usage
- `usage_voice` — monthly voice usage
- `network_quality` — customer/network monthly measurements
- `complaints` — customer complaint records
- `customer_feedback` — customer feedback records
- `support_tickets` — customer support interactions
- `devices` — customer device records
- `retention_campaigns` — customer retention campaign interactions

## Data Quality / Audit Table

- `data_quality_issue_log` — records known data-quality issues in the source data

## Next Validation

The classification will be refined by checking the grain, row counts, and business keys of each table before creating the final Power BI data model.

Step 5C — Determine the grain of each table.
The grain simply means:

What does one row represent?

In [13]:
# Step 5C — NexaTel Table Grain Overview

table_grain = {
    "customers": "One customer record",
    "plans": "One telecom plan",
    "cities": "One city",
    "states": "One state",
    "regions": "One region",
    "stores": "One store",
    "employees": "One employee",
    "marketing_campaigns": "One marketing campaign",
    "billing": "One invoice",
    "payments": "One payment",
    "subscriptions": "One customer subscription",
    "contracts": "One customer contract",
    "plan_history": "One customer plan change",
    "recharges": "One recharge transaction",
    "usage_data": "One customer-month data usage record",
    "usage_sms": "One customer-month SMS usage record",
    "usage_voice": "One customer-month voice usage record",
    "network_quality": "One customer-city-month network quality record",
    "complaints": "One customer complaint",
    "customer_feedback": "One customer feedback record",
    "support_tickets": "One customer support ticket",
    "devices": "One customer device",
    "retention_campaigns": "One customer retention campaign interaction",
    "data_quality_issue_log": "One data-quality issue type for a table"
}

print("NEXATEL TABLE GRAIN")
print("=" * 90)

for table, grain in table_grain.items():
    df = tables[table]
    
    print(
        f"{table:25} | "
        f"Rows: {len(df):7} | "
        f"Grain: {grain}"
    )

NEXATEL TABLE GRAIN
customers                 | Rows:   19076 | Grain: One customer record
plans                     | Rows:      25 | Grain: One telecom plan
cities                    | Rows:      68 | Grain: One city
states                    | Rows:      36 | Grain: One state
regions                   | Rows:       4 | Grain: One region
stores                    | Rows:    2180 | Grain: One store
employees                 | Rows:     800 | Grain: One employee
marketing_campaigns       | Rows:      40 | Grain: One marketing campaign
billing                   | Rows:  115313 | Grain: One invoice
payments                  | Rows:   92362 | Grain: One payment
subscriptions             | Rows:   20523 | Grain: One customer subscription
contracts                 | Rows:   10607 | Grain: One customer contract
plan_history              | Rows:   19349 | Grain: One customer plan change
recharges                 | Rows:  146501 | Grain: One recharge transaction
usage_data                | Row

# Step 5C — Table Grain Validation Findings

The grain of all 24 NexaTel tables has been documented.

The analysis confirms that the tables contain different levels of business activity, including:

- Customer-level records
- Transaction-level records
- Monthly usage records
- Customer interaction records
- Reference/master data

The `customers` table contains 19,076 raw rows but 19,000 unique `customer_id` values because 76 exact duplicate customer records were identified.

These duplicate records will be handled during the data-cleaning stage without modifying the original raw CSV files.

The identified grain of each table will be used to determine the appropriate fact and dimension structure for the final churn analytics model.



# Step 5D — Core Tables for Churn Analysis

The NexaTel data model contains 24 source tables. For churn analytics, the tables are grouped according to their analytical importance and business role.

## Core Customer Dimension

- `customers`

Contains customer demographics, location, acquisition information, plan information, tenure, customer status, and churn date.

## Core Reference Dimensions

- `plans`
- `cities`
- `states`
- `regions`

These tables provide plan and geographical attributes used to analyze churn patterns.

## Core Churn and Customer Activity Tables

- `subscriptions`
- `usage_data`
- `usage_voice`
- `usage_sms`
- `billing`
- `payments`
- `complaints`
- `support_tickets`
- `network_quality`
- `customer_feedback`
- `retention_campaigns`
- `recharges`
- `plan_history`

These tables contain customer activities, transactions, service interactions, usage behavior, and retention information that can be used to identify factors associated with churn.

## Supporting Business Tables

- `contracts`
- `devices`
- `stores`
- `employees`
- `marketing_campaigns`

These tables provide additional business context for customer and operational analysis.

## Data Quality / Audit Table

- `data_quality_issue_log`

Contains known source-data quality issues and is used to validate the data-cleaning process.

## Modeling Principle

The final Power BI model should not connect every source table directly to every other table.

Relationships will be designed according to the grain of each table to avoid ambiguous filtering and double-counting of measures.

The final model structure will be determined after reviewing the required churn KPIs and analytical questions.

# Step 6A — NexaTel Star Schema Design

## Modeling Approach

A customer-centered star-schema approach will be used for the NexaTel Customer Churn Analytics project.

The model will use shared dimensions to connect customer activity tables rather than creating direct relationships between multiple fact tables.

## Central Dimension

### `dim_customers`

The cleaned customer table will serve as the central customer dimension.

Primary key:

`customer_id`

It will contain customer demographics, customer status, churn information, acquisition details, location attributes, and customer segmentation information.

## Plan Dimension

### `dim_plans`

Primary key:

`plan_id`

Provides plan attributes such as plan name, product line, billing cycle, monthly charge, data quota, voice minutes, SMS allowance, and customer segment.

## Geography Dimensions

The geography information is represented by:

- `cities`
- `states`
- `regions`

These provide location, state, zone, region, and city-level attributes.

## Customer Activity Fact Tables

The following tables represent customer activities or transactions:

- `billing`
- `payments`
- `subscriptions`
- `recharges`
- `usage_data`
- `usage_sms`
- `usage_voice`
- `network_quality`
- `complaints`
- `customer_feedback`
- `support_tickets`
- `retention_campaigns`
- `plan_history`

Each fact table will retain its original business grain.

## Supporting Tables

The following tables provide additional business context:

- `contracts`
- `devices`
- `stores`
- `employees`
- `marketing_campaigns`

Their inclusion in the final Power BI model will depend on the analytical requirements.

## Modeling Principle

Fact tables should not be directly connected to other fact tables.

Shared dimensions should be used wherever possible to avoid:

- Many-to-many relationships
- Ambiguous filter paths
- Double-counting
- Incorrect KPI calculations

## Data Cleaning Requirement

The raw `customers` table contains 76 exact duplicate records.

Therefore, a cleaned `dim_customers` table with 19,000 unique customers will be created before establishing the final customer relationships.

The original raw CSV files will remain unchanged.

In [14]:
# Step 6B — Relationship Cardinality Check

relationships = [
    ("customers", "customer_id", "billing", "customer_id"),
    ("customers", "customer_id", "complaints", "customer_id"),
    ("customers", "customer_id", "contracts", "customer_id"),
    ("customers", "customer_id", "customer_feedback", "customer_id"),
    ("customers", "customer_id", "devices", "customer_id"),
    ("customers", "customer_id", "network_quality", "customer_id"),
    ("customers", "customer_id", "payments", "customer_id"),
    ("customers", "customer_id", "plan_history", "customer_id"),
    ("customers", "customer_id", "recharges", "customer_id"),
    ("customers", "customer_id", "retention_campaigns", "customer_id"),
    ("customers", "customer_id", "subscriptions", "customer_id"),
    ("customers", "customer_id", "support_tickets", "customer_id"),
    ("customers", "customer_id", "usage_data", "customer_id"),
    ("customers", "customer_id", "usage_sms", "customer_id"),
    ("customers", "customer_id", "usage_voice", "customer_id"),

    ("plans", "plan_id", "contracts", "plan_id"),
    ("plans", "plan_id", "subscriptions", "plan_id"),
    ("plans", "plan_id", "recharges", "plan_id"),

    ("cities", "city_id", "customers", "city_id"),
    ("cities", "city_id", "stores", "city_id"),

    ("states", "state_id", "cities", "state_id"),
    ("states", "state_id", "stores", "state_id"),

    ("regions", "region_id", "cities", "region_id"),
    ("regions", "region_id", "stores", "region_id"),
    ("regions", "region_id", "customers", "region_id"),
    ("regions", "region_id", "employees", "region_id"),

    ("stores", "store_id", "employees", "store_id"),
    ("employees", "employee_id", "support_tickets", "assigned_employee_id")
]

print("RELATIONSHIP CARDINALITY CHECK")
print("=" * 100)

for parent_table, parent_key, child_table, child_key in relationships:

    parent_df = tables[parent_table]
    child_df = tables[child_table]

    parent_unique = parent_df[parent_key].nunique()
    child_unique = child_df[child_key].nunique()
    child_rows = len(child_df)

    if child_unique == child_rows:
        cardinality = "Potential 1:1"
    else:
        cardinality = "Potential 1:*"

    print(
        f"{parent_table:18} ({parent_key:20}) "
        f"→ {child_table:22} ({child_key:20}) | "
        f"{cardinality}"
    )

RELATIONSHIP CARDINALITY CHECK
customers          (customer_id         ) → billing                (customer_id         ) | Potential 1:*
customers          (customer_id         ) → complaints             (customer_id         ) | Potential 1:*
customers          (customer_id         ) → contracts              (customer_id         ) | Potential 1:1
customers          (customer_id         ) → customer_feedback      (customer_id         ) | Potential 1:*
customers          (customer_id         ) → devices                (customer_id         ) | Potential 1:1
customers          (customer_id         ) → network_quality        (customer_id         ) | Potential 1:*
customers          (customer_id         ) → payments               (customer_id         ) | Potential 1:*
customers          (customer_id         ) → plan_history           (customer_id         ) | Potential 1:*
customers          (customer_id         ) → recharges              (customer_id         ) | Potential 1:*
customers      

# Step 6C — Investigating Potential 1:1 Relationships

The cardinality check identified three relationships that appear to be one-to-one based on the current data:

1. `customers.customer_id` → `contracts.customer_id`
2. `customers.customer_id` → `devices.customer_id`
3. `customers.customer_id` → `retention_campaigns.customer_id`

A potential 1:1 result does not automatically mean that the relationship should be modeled as 1:1.

The business key and table grain must also be considered.

For example:

- `contracts` has `contract_id` as its unique identifier.
- `devices` has `device_id` as its unique identifier.
- `retention_campaigns` has `campaign_id` as its unique identifier.

Therefore, these tables represent separate business entities or activities even when each customer currently appears only once.

The next check will determine the number of unique customers represented in each table and whether any customers have multiple records.

In [15]:
# Step 6C — Investigate Potential 1:1 Relationships

check_tables = ["contracts", "devices", "retention_campaigns"]

print("POTENTIAL 1:1 RELATIONSHIP INVESTIGATION")
print("=" * 90)

for table in check_tables:

    df = tables[table]

    customer_counts = df.groupby("customer_id").size()

    customers_with_multiple = (customer_counts > 1).sum()
    max_records = customer_counts.max()

    print(f"\n{table}")
    print("-" * 50)
    print("Total rows:", len(df))
    print("Unique customers:", df["customer_id"].nunique())
    print("Customers with multiple records:", customers_with_multiple)
    print("Maximum records for one customer:", max_records)

POTENTIAL 1:1 RELATIONSHIP INVESTIGATION

contracts
--------------------------------------------------
Total rows: 10607
Unique customers: 10607
Customers with multiple records: 0
Maximum records for one customer: 1

devices
--------------------------------------------------
Total rows: 19000
Unique customers: 19000
Customers with multiple records: 0
Maximum records for one customer: 1

retention_campaigns
--------------------------------------------------
Total rows: 6475
Unique customers: 6475
Customers with multiple records: 0
Maximum records for one customer: 1


# Step 6C — Potential 1:1 Relationship Findings

The investigation confirmed that the following tables currently contain exactly one record per customer:

| Table | Rows | Unique Customers | Business Key |
|---|---:|---:|---|
| contracts | 10,607 | 10,607 | contract_id |
| devices | 19,000 | 19,000 | device_id |
| retention_campaigns | 6,475 | 6,475 | campaign_id |

No customer has more than one record in any of these three tables in the current dataset.

However, these tables represent separate business entities or activities and have their own unique identifiers.

Therefore, they will remain separate tables rather than being merged into the `customers` table.

The current dataset supports a 1:1 customer relationship for these tables, but the model should preserve their independent business grain.


----------------------------------------------------------------------------------------------
# Step 6D — Create Clean Customer Dimension

The raw `customers` table contains 19,076 rows and 19,000 unique `customer_id` values.

The data-quality investigation identified 76 duplicate customer records.

For the analytical model, a clean customer dimension is required so that `customer_id` can function as a unique primary key on the "one" side of relationships.

A new `dim_customers` DataFrame will therefore be created by removing exact duplicate customer records.

The original `customers` DataFrame and `customers.csv` file will remain unchanged.

In [16]:
# Step 6D — Create Clean Customer Dimension

customers_raw = tables["customers"]

# Remove exact duplicate customer records
dim_customers = customers_raw.drop_duplicates().copy()

print("CUSTOMER DIMENSION VALIDATION")
print("=" * 80)

print("Raw customer rows:", len(customers_raw))
print("Clean dimension rows:", len(dim_customers))
print("Unique customer IDs:", dim_customers["customer_id"].nunique())
print("Duplicate customer IDs:", dim_customers["customer_id"].duplicated().sum())
print("Null customer IDs:", dim_customers["customer_id"].isna().sum())

CUSTOMER DIMENSION VALIDATION
Raw customer rows: 19076
Clean dimension rows: 19000
Unique customer IDs: 19000
Duplicate customer IDs: 0
Null customer IDs: 0


----------------------------------------------------------------------------------
# Step 6D — Customer Dimension Validation Result

The clean customer dimension `dim_customers` was successfully created from the raw `customers` table.

Validation results:

- Raw customer rows: 19,076
- Clean customer rows: 19,000
- Unique `customer_id` values: 19,000
- Duplicate `customer_id` values: 0
- Null `customer_id` values: 0

The 76 duplicate customer records identified during data-quality investigation were removed from the analytical dimension.

The original `customers` table and source CSV remain unchanged.

`dim_customers.customer_id` can now serve as a unique primary key for the customer dimension.


--------------------------------------------------------------------------------------------------
# Step 6E — Final Validated Relationship Map

The final relationship map is based on the validated primary keys, foreign keys, table grain, and the cleaned customer dimension.

## Customer-Centered Relationships

The cleaned `dim_customers` table contains one unique row per customer and serves as the primary customer dimension.

| Parent | Key | Child | Foreign Key | Cardinality |
|---|---|---|---|---|
| dim_customers | customer_id | billing | customer_id | 1:* |
| dim_customers | customer_id | complaints | customer_id | 1:* |
| dim_customers | customer_id | contracts | customer_id | 1:* |
| dim_customers | customer_id | customer_feedback | customer_id | 1:* |
| dim_customers | customer_id | devices | customer_id | 1:* |
| dim_customers | customer_id | network_quality | customer_id | 1:* |
| dim_customers | customer_id | payments | customer_id | 1:* |
| dim_customers | customer_id | plan_history | customer_id | 1:* |
| dim_customers | customer_id | recharges | customer_id | 1:* |
| dim_customers | customer_id | retention_campaigns | customer_id | 1:* |
| dim_customers | customer_id | subscriptions | customer_id | 1:* |
| dim_customers | customer_id | support_tickets | customer_id | 1:* |
| dim_customers | customer_id | usage_data | customer_id | 1:* |
| dim_customers | customer_id | usage_sms | customer_id | 1:* |
| dim_customers | customer_id | usage_voice | customer_id | 1:* |

Although some tables currently contain one row per customer, they remain separate because they represent different business entities and have their own business keys.

## Plan Relationships

| Parent | Key | Child | Foreign Key |
|---|---|---|---|
| plans | plan_id | subscriptions | plan_id |
| plans | plan_id | contracts | plan_id |
| plans | plan_id | recharges | plan_id |

`plan_history` contains two references to `plans`:

- `old_plan_id`
- `new_plan_id`

These relationships require special handling because both columns reference the same parent table.

## Geography Relationships

| Parent | Key | Child | Foreign Key |
|---|---|---|---|
| states | state_id | cities | state_id |
| regions | region_id | cities | region_id |
| cities | city_id | stores | city_id |
| states | state_id | stores | state_id |
| regions | region_id | stores | region_id |

## Employee Relationships

| Parent | Key | Child | Foreign Key |
|---|---|---|---|
| stores | store_id | employees | store_id |
| regions | region_id | employees | region_id |
| employees | employee_id | support_tickets | assigned_employee_id |

## Billing → Payments

| Parent | Key | Child | Foreign Key | Cardinality |
|---|---|---|---|---|
| billing | invoice_id | payments | invoice_id | 1:* |

This relationship contains 184 invalid payment invoice references, identified during foreign-key validation.

## Data Quality

The `data_quality_issue_log` table will remain an audit/reference table and will not be part of the analytical relationship model.

## Modeling Principle

The final Power BI model will use one-to-many relationships wherever the validated grain supports them.

Fact/activity tables will not be directly connected to other fact/activity tables unless a specific business requirement justifies the relationship.

The model will be designed to minimize ambiguous filter paths and prevent double-counting.

------------------------------------------------------------------------------------------
# Step 6F — Date Dimension Design

A dedicated date dimension will be created for time-based analysis across the NexaTel data model.

The date dimension will support:

- Year
- Quarter
- Month
- Month Number
- Month-Year
- Week
- Day
- Day of Week

The date dimension will provide a consistent time framework for analyzing:

- Customer churn
- Billing and payments
- Recharges
- Customer complaints
- Customer feedback
- Support tickets
- Network quality
- Customer usage
- Subscriptions
- Plan changes
- Retention campaigns

The raw date columns in the source tables will remain unchanged.

A separate `dim_date` table will be created for analytical modeling.

In [17]:
# Step 6F — Create Date Dimension

import pandas as pd

# Collect valid dates from important date columns
date_columns = {
    "customers": ["acquisition_date", "churn_date"],
    "billing": ["billing_date", "due_date"],
    "payments": ["payment_date"],
    "recharges": ["recharge_date"],
    "complaints": ["complaint_date", "resolution_date"],
    "customer_feedback": ["feedback_date"],
    "subscriptions": ["start_date", "end_date"],
    "contracts": ["start_date", "end_date"],
    "plan_history": ["change_date"],
    "support_tickets": ["created_date", "resolution_date"],
    "devices": ["purchase_date"],
    "retention_campaigns": ["contact_date"],
    "marketing_campaigns": ["start_date", "end_date"],
    "employees": ["hire_date"],
    "stores": ["opened_date"]
}

all_dates = []

for table, columns in date_columns.items():
    for column in columns:
        if column in tables[table].columns:
            dates = pd.to_datetime(
                tables[table][column],
                errors="coerce",
                dayfirst=True
            ).dropna()

            all_dates.extend(dates.tolist())

# Determine date range
min_date = min(all_dates)
max_date = max(all_dates)

print("Minimum date:", min_date.date())
print("Maximum date:", max_date.date())

# Create date dimension
date_range = pd.date_range(
    start=min_date,
    end=max_date,
    freq="D"
)

dim_date = pd.DataFrame({
    "date": date_range
})

dim_date["year"] = dim_date["date"].dt.year
dim_date["quarter"] = "Q" + dim_date["date"].dt.quarter.astype(str)
dim_date["month_number"] = dim_date["date"].dt.month
dim_date["month_name"] = dim_date["date"].dt.month_name()
dim_date["month_year"] = dim_date["date"].dt.strftime("%Y-%m")
dim_date["week_number"] = dim_date["date"].dt.isocalendar().week.astype(int)
dim_date["day"] = dim_date["date"].dt.day
dim_date["day_name"] = dim_date["date"].dt.day_name()

print("\nDATE DIMENSION")
print("=" * 80)
print("Rows:", len(dim_date))
print("Columns:", len(dim_date.columns))
print("Date range:", dim_date["date"].min().date(), "to", dim_date["date"].max().date())
print("Duplicate dates:", dim_date["date"].duplicated().sum())
print("Null dates:", dim_date["date"].isna().sum())

print("\nFirst 5 rows:")
display(dim_date.head())

Minimum date: 2010-01-03
Maximum date: 2029-01-28

DATE DIMENSION
Rows: 6966
Columns: 9
Date range: 2010-01-03 to 2029-01-28
Duplicate dates: 0
Null dates: 0

First 5 rows:


,date,year,quarter,month_number,month_name,month_year,week_number,day,day_name
0,2010-01-03,2010,Q1,1,January,2010-01,53,3,Sunday
1,2010-01-04,2010,Q1,1,January,2010-01,1,4,Monday
2,2010-01-05,2010,Q1,1,January,2010-01,1,5,Tuesday
3,2010-01-06,2010,Q1,1,January,2010-01,1,6,Wednesday
4,2010-01-07,2010,Q1,1,January,2010-01,1,7,Thursday


# Step 6F — Date Dimension Validation Result

The `dim_date` table was successfully created from the date fields available across the NexaTel source tables.

Validation results:

- Date range: 2010-01-03 to 2029-01-28
- Total dates: 6,966
- Duplicate dates: 0
- Null dates: 0
- Date attributes created: 9

The date dimension provides a consistent time framework for year, quarter, month, week, and daily analysis.

The source data contains dates extending into 2029. These dates will be reviewed during the data-quality cleaning stage to determine whether they represent valid future records or source-data issues.

The `dim_date` table will be used as the central date dimension in the final analytical model.


# Step 7A — Customer Data Quality Investigation

The customer table contains several data-quality issues identified in the
`data_quality_issue_log`.

The issues include:

- Missing email
- Missing address
- Missing income
- Invalid phone numbers
- Invalid email addresses
- Incorrect PIN codes
- Misspelled city values
- Inconsistent capitalization
- Impossible ages
- Mixed date formats
- Duplicate customer records

The duplicate customer records have already been identified and removed from
the analytical `dim_customers` DataFrame.

The remaining issues will be investigated before applying cleaning rules.

The original `customers.csv` file will remain unchanged.

In [18]:
# Step 7A — Customer Data Quality Investigation

customers = tables["customers"].copy()

print("CUSTOMER DATA QUALITY INVESTIGATION")
print("=" * 90)

# Missing values
print("\n1. MISSING VALUES")
print("-" * 50)

missing = customers.isna().sum()
missing = missing[missing > 0]

print(missing)


# Duplicate customer IDs
print("\n2. DUPLICATE CUSTOMER IDs")
print("-" * 50)

print(
    "Duplicate customer IDs:",
    customers["customer_id"].duplicated().sum()
)


# Age range
print("\n3. AGE RANGE")
print("-" * 50)

print("Minimum age:", customers["age"].min())
print("Maximum age:", customers["age"].max())

print("\nPotential impossible ages:")

invalid_age = customers[
    (customers["age"] < 18) |
    (customers["age"] > 100)
]

print("Rows:", len(invalid_age))


# Email format
print("\n4. EMAIL FORMAT CHECK")
print("-" * 50)

email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_email = customers[
    customers["email"].notna() &
    ~customers["email"].astype(str).str.match(email_pattern)
]

print("Potential invalid emails:", len(invalid_email))


# Phone format
print("\n5. PHONE FORMAT CHECK")
print("-" * 50)

phone_digits = customers["phone_number"].astype(str).str.replace(
    r"\D", "", regex=True
)

invalid_phone = customers[
    customers["phone_number"].notna() &
    ~phone_digits.str.len().eq(10)
]

print("Potential invalid phone numbers:", len(invalid_phone))


# PIN format
print("\n6. PIN CODE CHECK")
print("-" * 50)

pin_digits = customers["pin_code"].astype(str).str.replace(
    r"\D", "", regex=True
)

invalid_pin = customers[
    customers["pin_code"].notna() &
    ~pin_digits.str.len().eq(6)
]

print("Potential invalid PIN codes:", len(invalid_pin))


# Date parsing
print("\n7. DATE FORMAT CHECK")
print("-" * 50)

acquisition_parsed = pd.to_datetime(
    customers["acquisition_date"],
    errors="coerce",
    dayfirst=True
)

churn_parsed = pd.to_datetime(
    customers["churn_date"],
    errors="coerce",
    dayfirst=True
)

print(
    "Acquisition dates that could not be parsed:",
    acquisition_parsed.isna().sum()
)

print(
    "Churn dates that could not be parsed:",
    churn_parsed.isna().sum()
)

CUSTOMER DATA QUALITY INVESTIGATION

1. MISSING VALUES
--------------------------------------------------
email                  745
address                380
annual_income_inr      954
churn_date           15560
dtype: int64

2. DUPLICATE CUSTOMER IDs
--------------------------------------------------
Duplicate customer IDs: 76

3. AGE RANGE
--------------------------------------------------
Minimum age: -5
Maximum age: 220

Potential impossible ages:
Rows: 38

4. EMAIL FORMAT CHECK
--------------------------------------------------
Potential invalid emails: 286

5. PHONE FORMAT CHECK
--------------------------------------------------
Potential invalid phone numbers: 19076

6. PIN CODE CHECK
--------------------------------------------------
Potential invalid PIN codes: 191

7. DATE FORMAT CHECK
--------------------------------------------------
Acquisition dates that could not be parsed: 383
Churn dates that could not be parsed: 15560


--------------------------------------------------------------
# Step 7B — Investigate Data Quality Discrepancies

The initial customer-quality checks were compared with the expected issue counts
from `data_quality_issue_log`.

Several counts differ slightly from the quality log.

These differences must be investigated before applying cleaning rules.

In particular, the phone-number validation rule produced 19,076 potential
invalid records, which indicates that the initial validation rule does not
match the source-data quality definition.

Therefore, no phone-number records will be modified based on this preliminary
check.

Missing `churn_date` values are also not automatically treated as errors because
customers who have not churned are expected to have no churn date.

The purpose of this step is to identify the correct validation rules before
cleaning the customer data.

In [19]:
# Step 7B — Investigate Customer Data Quality Discrepancies

print("CUSTOMER DATA QUALITY DISCREPANCY ANALYSIS")
print("=" * 90)

# 1. Inspect phone number examples
print("\n1. PHONE NUMBER SAMPLE")
print("-" * 50)

print(
    customers["phone_number"]
    .dropna()
    .astype(str)
    .head(20)
    .to_string(index=False)
)


# 2. Inspect email examples flagged as invalid
print("\n2. INVALID EMAIL SAMPLE")
print("-" * 50)

print(
    invalid_email[["customer_id", "email"]]
    .head(20)
    .to_string(index=False)
)


# 3. Inspect invalid PIN examples
print("\n3. INVALID PIN SAMPLE")
print("-" * 50)

print(
    invalid_pin[["customer_id", "pin_code"]]
    .head(20)
    .to_string(index=False)
)


# 4. Inspect impossible ages
print("\n4. IMPOSSIBLE AGE RECORDS")
print("-" * 50)

print(
    invalid_age[["customer_id", "age", "date_of_birth"]]
    .to_string(index=False)
)


# 5. Inspect acquisition dates that failed parsing
print("\n5. UNPARSED ACQUISITION DATE SAMPLE")
print("-" * 50)

unparsed_acquisition = customers[
    acquisition_parsed.isna()
]

print(
    unparsed_acquisition[
        ["customer_id", "acquisition_date"]
    ]
    .head(20)
    .to_string(index=False)
)

CUSTOMER DATA QUALITY DISCREPANCY ANALYSIS

1. PHONE NUMBER SAMPLE
--------------------------------------------------
916647481156
918116536619
918958153134
917763920098
916787478273
916083413392
916529964485
918039201799
918153754834
916422921624
       57059
919003843105
916911182239
918055320949
919447514418
918384315234
918575123117
917000186679
917399234440
918847239376

2. INVALID EMAIL SAMPLE
--------------------------------------------------
customer_id           email
   C0000204 user544_at_mail
   C0000269 user123_at_mail
   C0000482 user615_at_mail
   C0000718 user428_at_mail
   C0000823 user690_at_mail
   C0000830 user648_at_mail
   C0000831 user521_at_mail
   C0000858 user564_at_mail
   C0000870 user731_at_mail
   C0000999 user902_at_mail
   C0001030 user227_at_mail
   C0001045 user918_at_mail
   C0001124 user614_at_mail
   C0001151 user519_at_mail
   C0001192 user350_at_mail
   C0001193 user728_at_mail
   C0001206 user600_at_mail
   C0001311 user408_at_mail
   C0001436  u

----------------------------------------------------------
# Step 7C — Customer Data Cleaning

The customer data will be cleaned using the findings from the investigation.

Cleaning principles:

1. Remove exact duplicate customer records.
2. Standardize email and phone fields.
3. Flag invalid email and phone values rather than inventing replacement values.
4. Standardize PIN codes and flag invalid PINs.
5. Recalculate age from date of birth where possible.
6. Standardize mixed date formats.
7. Preserve legitimate missing values such as churn_date for active customers.
8. Preserve the original raw customer table unchanged.

The resulting table will be used as the analytical customer dimension.

In [20]:
# Step 7C — Clean Customer Dimension

customers_clean = tables["customers"].copy()

print("CUSTOMER CLEANING")
print("=" * 80)

# --------------------------------------------------
# 1. Remove exact duplicate customer records
# --------------------------------------------------

before = len(customers_clean)

customers_clean = customers_clean.drop_duplicates()

after = len(customers_clean)

print("Exact duplicate rows removed:", before - after)


# --------------------------------------------------
# 2. Standardize text fields
# --------------------------------------------------

text_columns = [
    "first_name",
    "last_name",
    "gender",
    "occupation",
    "customer_segment",
    "product_line",
    "acquisition_channel",
    "customer_status"
]

for col in text_columns:
    customers_clean[col] = (
        customers_clean[col]
        .astype("string")
        .str.strip()
        .str.title()
    )


# --------------------------------------------------
# 3. Clean email
# --------------------------------------------------

customers_clean["email"] = (
    customers_clean["email"]
    .astype("string")
    .str.strip()
    .str.lower()
)

email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_email_mask = (
    customers_clean["email"].notna()
    & ~customers_clean["email"].str.match(
        email_pattern,
        na=False
    )
)

customers_clean.loc[
    invalid_email_mask,
    "email"
] = pd.NA

print("Invalid emails converted to null:", invalid_email_mask.sum())


# --------------------------------------------------
# 4. Clean phone numbers
# --------------------------------------------------

customers_clean["phone_number"] = (
    customers_clean["phone_number"]
    .astype("string")
    .str.strip()
)

phone_digits = customers_clean["phone_number"].str.replace(
    r"\D",
    "",
    regex=True
)

valid_phone_mask = phone_digits.str.len().eq(12)

invalid_phone_mask = (
    customers_clean["phone_number"].notna()
    & ~valid_phone_mask
)

customers_clean.loc[
    invalid_phone_mask,
    "phone_number"
] = pd.NA

print(
    "Invalid phone numbers converted to null:",
    invalid_phone_mask.sum()
)


# --------------------------------------------------
# 5. Clean PIN code
# --------------------------------------------------

pin_digits = (
    customers_clean["pin_code"]
    .astype("string")
    .str.replace(r"\D", "", regex=True)
)

valid_pin_mask = pin_digits.str.len().eq(6)

invalid_pin_mask = (
    customers_clean["pin_code"].notna()
    & ~valid_pin_mask
)

customers_clean.loc[
    invalid_pin_mask,
    "pin_code"
] = pd.NA

customers_clean["pin_code"] = pin_digits.where(
    valid_pin_mask,
    pd.NA
)

print("Invalid PINs converted to null:", invalid_pin_mask.sum())


# --------------------------------------------------
# 6. Standardize dates
# --------------------------------------------------

customers_clean["acquisition_date"] = pd.to_datetime(
    customers_clean["acquisition_date"],
    format="mixed",
    errors="coerce"
)

customers_clean["churn_date"] = pd.to_datetime(
    customers_clean["churn_date"],
    format="mixed",
    errors="coerce"
)

customers_clean["date_of_birth"] = pd.to_datetime(
    customers_clean["date_of_birth"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)


# --------------------------------------------------
# 7. Recalculate invalid ages from date of birth
# --------------------------------------------------

reference_date = pd.Timestamp("2026-08-24")

dob = customers_clean["date_of_birth"]

calculated_age = (
    reference_date.year
    - dob.dt.year
    - (
        (
            dob.dt.month > reference_date.month
        )
        |
        (
            (dob.dt.month == reference_date.month)
            &
            (dob.dt.day > reference_date.day)
        )
    ).astype(int)
)

invalid_age_mask = (
    (customers_clean["age"] < 18)
    | (customers_clean["age"] > 100)
)

customers_clean.loc[
    invalid_age_mask,
    "age"
] = calculated_age[invalid_age_mask]

print(
    "Invalid ages corrected:",
    invalid_age_mask.sum()
)


# --------------------------------------------------
# 8. Final validation
# --------------------------------------------------

print("\nFINAL CUSTOMER VALIDATION")
print("=" * 80)

print("Rows:", len(customers_clean))

print(
    "Unique customer IDs:",
    customers_clean["customer_id"].nunique()
)

print(
    "Duplicate customer IDs:",
    customers_clean["customer_id"].duplicated().sum()
)

remaining_invalid_age = (
    (customers_clean["age"] < 18)
    | (customers_clean["age"] > 100)
).sum()

print(
    "Invalid ages remaining:",
    remaining_invalid_age
)

print(
    "Null emails:",
    customers_clean["email"].isna().sum()
)

print(
    "Null phone numbers:",
    customers_clean["phone_number"].isna().sum()
)

print(
    "Null PIN codes:",
    customers_clean["pin_code"].isna().sum()
)

print(
    "Null churn dates:",
    customers_clean["churn_date"].isna().sum()
)

print("\nCleaning complete.")

CUSTOMER CLEANING
Exact duplicate rows removed: 76
Invalid emails converted to null: 285
Invalid phone numbers converted to null: 228
Invalid PINs converted to null: 190
Invalid ages corrected: 38

FINAL CUSTOMER VALIDATION
Rows: 19000
Unique customer IDs: 19000
Duplicate customer IDs: 0
Invalid ages remaining: 0
Null emails: 1029
Null phone numbers: 228
Null PIN codes: 190
Null churn dates: 15494

Cleaning complete.



========================================================================================
# Step 7C — Customer Cleaning Validation

The customer table was cleaned without modifying the original CSV file.

Cleaning actions performed:

- Removed 76 duplicate customer records.
- Corrected 285 invalid email values by converting them to null.
- Corrected 228 invalid phone numbers by converting them to null.
- Corrected 190 invalid PIN values by converting them to null.
- Corrected 38 impossible age values using date of birth.
- Standardized customer text fields.
- Standardized customer date fields.

## Final Validation

- Clean customer rows: 19,000
- Unique customer IDs: 19,000
- Duplicate customer IDs: 0
- Invalid ages remaining: 0
- Null emails: 1,029
- Null phone numbers: 228
- Null PIN codes: 190

The cleaned customer table is suitable for use as the customer dimension
(`dim_customers`) in the analytical model.

The original `customers.csv` remains unchanged.

In [21]:
# Store cleaned customer dimension

dim_customers = customers_clean.copy()

print("dim_customers created successfully")
print("Rows:", len(dim_customers))
print("Unique customers:", dim_customers["customer_id"].nunique())

dim_customers created successfully
Rows: 19000
Unique customers: 19000


In [22]:
# Save cleaned customer data to CSV

customers_clean.to_csv(
    "cleaned_data/customers_clean.csv",
    index=False
)

print("Cleaned customer data saved successfully.")
print("Rows:", len(customers_clean))
print("Columns:", len(customers_clean.columns))

Cleaned customer data saved successfully.
Rows: 19000
Columns: 25


In [23]:
# Verify the saved CSV

customers_check = pd.read_csv("cleaned_data/customers_clean.csv")

print("CUSTOMERS CLEAN CSV VALIDATION")
print("=" * 80)
print("Rows:", len(customers_check))
print("Columns:", len(customers_check.columns))
print("Unique customer IDs:", customers_check["customer_id"].nunique())
print("Duplicate customer IDs:", customers_check["customer_id"].duplicated().sum())

CUSTOMERS CLEAN CSV VALIDATION
Rows: 19000
Columns: 25
Unique customer IDs: 19000
Duplicate customer IDs: 0


------------------------------------------------------------------------------------------------------
# Step 7D — Billing and Payments Data Quality Investigation

Billing and payment data are critical for revenue, payment-status, and
customer-value analysis.

The data-quality log identifies the following issues:

## Billing

- Duplicate invoices: 344
- Incorrect GST: 1,149
- Negative invoice amounts: 229
- Future billing dates: 229

## Payments

- Duplicate payments: 276
- Broken invoice foreign keys: 184

The original CSV files will remain unchanged.

The billing and payment tables will first be investigated before cleaning.
This prevents valid business records from being incorrectly removed.

In [24]:
# Step 7D — Billing Investigation

billing = tables["billing"].copy()

print("BILLING DATA QUALITY INVESTIGATION")
print("=" * 90)

# --------------------------------------------------
# 1. Duplicate invoices
# --------------------------------------------------

print("\n1. DUPLICATE INVOICE IDs")
print("-" * 50)

print(
    "Rows:",
    len(billing)
)

print(
    "Unique invoice IDs:",
    billing["invoice_id"].nunique()
)

print(
    "Duplicate invoice IDs:",
    billing["invoice_id"].duplicated().sum()
)

print(
    "Exact duplicate billing rows:",
    billing.duplicated().sum()
)


# --------------------------------------------------
# 2. Negative amounts
# --------------------------------------------------

print("\n2. NEGATIVE INVOICE AMOUNTS")
print("-" * 50)

negative_billing = billing[
    billing["total_amount_inr"] < 0
]

print(
    "Negative total amounts:",
    len(negative_billing)
)

print(
    negative_billing[
        [
            "invoice_id",
            "customer_id",
            "base_amount_inr",
            "gst_amount_inr",
            "total_amount_inr"
        ]
    ].head(20).to_string(index=False)
)


# --------------------------------------------------
# 3. GST validation
# --------------------------------------------------

print("\n3. GST VALIDATION")
print("-" * 50)

# Expected GST based on base amount
billing["expected_gst"] = (
    billing["base_amount_inr"] * 0.18
)

billing["gst_difference"] = (
    billing["gst_amount_inr"]
    - billing["expected_gst"]
).abs()

incorrect_gst = billing[
    billing["gst_difference"] > 0.01
]

print(
    "Potential incorrect GST records:",
    len(incorrect_gst)
)

print(
    incorrect_gst[
        [
            "invoice_id",
            "base_amount_inr",
            "gst_amount_inr",
            "expected_gst",
            "total_amount_inr"
        ]
    ].head(20).to_string(index=False)
)


# --------------------------------------------------
# 4. Billing date validation
# --------------------------------------------------

print("\n4. FUTURE BILLING DATES")
print("-" * 50)

billing["billing_date_parsed"] = pd.to_datetime(
    billing["billing_date"],
    format="mixed",
    errors="coerce"
)

future_billing = billing[
    billing["billing_date_parsed"]
    > pd.Timestamp("2026-08-24")
]

print(
    "Future billing dates:",
    len(future_billing)
)

print(
    future_billing[
        [
            "invoice_id",
            "customer_id",
            "billing_date"
        ]
    ].head(20).to_string(index=False)
)

BILLING DATA QUALITY INVESTIGATION

1. DUPLICATE INVOICE IDs
--------------------------------------------------
Rows: 115313
Unique invoice IDs: 114969
Duplicate invoice IDs: 344
Exact duplicate billing rows: 344

2. NEGATIVE INVOICE AMOUNTS
--------------------------------------------------
Negative total amounts: 229
 invoice_id customer_id  base_amount_inr  gst_amount_inr  total_amount_inr
INV00000353    C0000074           611.62          110.09           -721.71
INV00000560    C0000102           639.46          115.10           -754.56
INV00000717    C0000124          1324.07          238.33          -1562.40
INV00000868    C0000156          1408.69          253.56          -1662.25
INV00001031    C0000192           531.10           95.60           -626.70
INV00001901    C0000331          1519.83          273.57          -1793.40
INV00003811    C0000696          3909.14          703.65          -4612.79
INV00004480    C0000829          1515.23          272.74          -1787.97
INV0

In [25]:
# Step 7D — Payments Investigation

payments = tables["payments"].copy()

print("PAYMENTS DATA QUALITY INVESTIGATION")
print("=" * 90)

# --------------------------------------------------
# 1. Duplicate payments
# --------------------------------------------------

print("\n1. DUPLICATE PAYMENT IDs")
print("-" * 50)

print(
    "Rows:",
    len(payments)
)

print(
    "Unique payment IDs:",
    payments["payment_id"].nunique()
)

print(
    "Duplicate payment IDs:",
    payments["payment_id"].duplicated().sum()
)

print(
    "Exact duplicate payment rows:",
    payments.duplicated().sum()
)


# --------------------------------------------------
# 2. Broken invoice foreign keys
# --------------------------------------------------

print("\n2. BROKEN PAYMENT → BILLING REFERENCES")
print("-" * 50)

valid_invoice_ids = set(
    billing["invoice_id"]
    .dropna()
    .astype(str)
)

invalid_payment_invoice = payments[
    ~payments["invoice_id"]
    .astype(str)
    .isin(valid_invoice_ids)
]

print(
    "Invalid invoice references:",
    len(invalid_payment_invoice)
)

print(
    invalid_payment_invoice[
        [
            "payment_id",
            "invoice_id",
            "customer_id",
            "amount_inr",
            "payment_method",
            "payment_status"
        ]
    ].head(20).to_string(index=False)
)

PAYMENTS DATA QUALITY INVESTIGATION

1. DUPLICATE PAYMENT IDs
--------------------------------------------------
Rows: 92362
Unique payment IDs: 92086
Duplicate payment IDs: 276
Exact duplicate payment rows: 276

2. BROKEN PAYMENT → BILLING REFERENCES
--------------------------------------------------
Invalid invoice references: 184
 payment_id  invoice_id customer_id  amount_inr payment_method payment_status
PAY00000875 INV94560686    C0000199     1444.45    Credit Card        Success
PAY00001008 INV96995702    C0000232      723.82    Credit Card        Success
PAY00001475 INV99552429    C0000319     1439.82    Credit Card        Success
PAY00002113 INV98863464    C0000473      746.33            UPI        Success
PAY00002118 INV92113763    C0000477     1536.96           Cash        Success
PAY00002381 INV92607579    C0000533      817.30         Wallet        Success
PAY00002760 INV98698649    C0000628      850.38     Auto Debit        Success
PAY00003252 INV98048665    C0000733      

-----------------------------------------------------------------
# Step 7D — Billing and Payments Cleaning

The billing and payment tables were investigated for duplicate records,
invalid monetary values, incorrect GST, future dates, and broken foreign keys.

Cleaning principles:

- Remove only exact duplicate transaction rows.
- Correct calculable GST values using the expected 18% GST rate.
- Convert invalid negative invoice amounts to null.
- Convert future billing dates to null.
- Preserve payment records with broken invoice references, but set the
  invalid invoice ID to null.
- The original CSV files remain unchanged.
[
          Issue                  	Action
344  - duplicate invoices	 -     Remove exact duplicate rows,
229  - negative amounts       -  	  Convert invalid negative invoice amount fields to NaN rather than deleting invoice,
1,150 -incorrect GST	      -        Recalculate GST from base amount,
176 -  future billing dates	   -   Convert future dates to NaT,
276-duplicate payments	   -   Remove exact duplicate rows,
184 -  broken invoice references	-  Keep payment record but set invalid invoice_id to NaN]

Important: We are preserving the transaction rows wherever possible. We don't want to lose legitimate customer/payment history just because one field is bad.

In [26]:
# ============================================================
# STEP 7D — BILLING CLEANING
# ============================================================
import numpy as np

billing_clean = tables["billing"].copy()

print("BILLING CLEANING")
print("=" * 80)

# ------------------------------------------------------------
# 1. Remove exact duplicate billing rows
# ------------------------------------------------------------

before = len(billing_clean)

billing_clean = billing_clean.drop_duplicates()

removed_duplicates = before - len(billing_clean)

print("Exact duplicate billing rows removed:", removed_duplicates)


# ------------------------------------------------------------
# 2. Convert monetary columns to numeric
# ------------------------------------------------------------

money_columns = [
    "base_amount_inr",
    "gst_amount_inr",
    "total_amount_inr"
]

for col in money_columns:
    billing_clean[col] = pd.to_numeric(
        billing_clean[col],
        errors="coerce"
    )


# ------------------------------------------------------------
# 3. Negative invoice amounts → null
# ------------------------------------------------------------

negative_mask = (
    billing_clean["total_amount_inr"] < 0
)

negative_count = negative_mask.sum()

billing_clean.loc[
    negative_mask,
    [
        "base_amount_inr",
        "gst_amount_inr",
        "total_amount_inr"
    ]
] = np.nan

print("Negative invoice records corrected:", negative_count)


# ------------------------------------------------------------
# 4. Correct GST
# ------------------------------------------------------------

billing_clean["gst_amount_inr"] = (
    billing_clean["base_amount_inr"] * 0.18
).round(2)

# Recalculate total amount
billing_clean["total_amount_inr"] = (
    billing_clean["base_amount_inr"]
    + billing_clean["gst_amount_inr"]
).round(2)

print("GST values recalculated using 18% GST.")


# ------------------------------------------------------------
# 5. Parse billing dates
# ------------------------------------------------------------

billing_clean["billing_date"] = pd.to_datetime(
    billing_clean["billing_date"],
    format="mixed",
    errors="coerce"
)

billing_clean["due_date"] = pd.to_datetime(
    billing_clean["due_date"],
    format="mixed",
    errors="coerce"
)


# ------------------------------------------------------------
# 6. Future billing dates → null
# ------------------------------------------------------------

reference_date = pd.Timestamp("2026-08-24")

future_mask = (
    billing_clean["billing_date"] > reference_date
)

future_count = future_mask.sum()

billing_clean.loc[
    future_mask,
    "billing_date"
] = pd.NaT

print("Future billing dates corrected:", future_count)


print("\nFinal billing rows:", len(billing_clean))
print("Unique invoice IDs:", billing_clean["invoice_id"].nunique())



BILLING CLEANING
Exact duplicate billing rows removed: 344
Negative invoice records corrected: 229
GST values recalculated using 18% GST.
Future billing dates corrected: 175

Final billing rows: 114969
Unique invoice IDs: 114969


In [27]:
# ============================================================
# SAVE CLEANED BILLING DATA
# ============================================================


billing_clean.to_csv(
    r"C:\Users\Abcom\OneDrive\Desktop\Nexatel_Customer_Churn_Analysis\cleaned_data\billing_clean.csv",
    index=False
)

print("Cleaned billing data saved successfully.")
print("File: billing_clean.csv")
print("Rows:", len(billing_clean))
print("Columns:", len(billing_clean.columns))

Cleaned billing data saved successfully.
File: billing_clean.csv
Rows: 114969
Columns: 9


In [28]:
# ============================================================
# STEP 7D — PAYMENTS CLEANING
# ============================================================

payments_clean = tables["payments"].copy()

print("PAYMENTS CLEANING")
print("=" * 80)

# ------------------------------------------------------------
# 1. Remove exact duplicate payment rows
# ------------------------------------------------------------

before = len(payments_clean)

payments_clean = payments_clean.drop_duplicates()

removed_duplicates = before - len(payments_clean)

print("Exact duplicate payment rows removed:", removed_duplicates)


# ------------------------------------------------------------
# 2. Validate invoice foreign keys
# ------------------------------------------------------------

valid_invoice_ids = set(
    billing_clean["invoice_id"]
    .dropna()
    .astype(str)
)

invalid_invoice_mask = ~(
    payments_clean["invoice_id"]
    .astype(str)
    .isin(valid_invoice_ids)
)

invalid_invoice_count = invalid_invoice_mask.sum()

payments_clean.loc[
    invalid_invoice_mask,
    "invoice_id"
] = np.nan

print(
    "Broken invoice references converted to null:",
    invalid_invoice_count
)


# ------------------------------------------------------------
# 3. Final payment validation
# ------------------------------------------------------------

print("\nFinal payment rows:", len(payments_clean))

print(
    "Unique payment IDs:",
    payments_clean["payment_id"].nunique()
)

print(
    "Null invoice IDs:",
    payments_clean["invoice_id"].isna().sum()
)

PAYMENTS CLEANING
Exact duplicate payment rows removed: 276
Broken invoice references converted to null: 184

Final payment rows: 92086
Unique payment IDs: 92086
Null invoice IDs: 184


-------------------------------------------------------------------
# Step 7E — Subscriptions, Contracts and Plan History Investigation

These tables describe customer plans, subscriptions, contracts and plan changes.

The investigation will validate:

- Duplicate records
- Missing plan IDs
- Invalid plan IDs
- Date consistency
- Subscription status
- Contract validity
- Plan history relationships

The original CSV files will remain unchanged until the investigation is complete.

In [29]:
# ============================================================
# STEP 7E — SUBSCRIPTIONS INVESTIGATION
# ============================================================

subscriptions = tables["subscriptions"].copy()

print("SUBSCRIPTIONS DATA QUALITY INVESTIGATION")
print("=" * 90)

# ------------------------------------------------------------
# 1. Basic information
# ------------------------------------------------------------

print("\n1. BASIC INFORMATION")
print("-" * 50)

print("Rows:", len(subscriptions))
print("Unique subscription IDs:", subscriptions["subscription_id"].nunique())
print("Duplicate subscription IDs:",
      subscriptions["subscription_id"].duplicated().sum())


# ------------------------------------------------------------
# 2. Missing values
# ------------------------------------------------------------

print("\n2. MISSING VALUES")
print("-" * 50)

print(
    subscriptions.isna().sum()
)


# ------------------------------------------------------------
# 3. Plan ID validation
# ------------------------------------------------------------

print("\n3. PLAN ID VALIDATION")
print("-" * 50)

valid_plan_ids = set(
    tables["plans"]["plan_id"]
    .dropna()
    .astype(str)
)

invalid_plan_mask = ~(
    subscriptions["plan_id"]
    .astype(str)
    .isin(valid_plan_ids)
)

print(
    "Invalid plan IDs:",
    invalid_plan_mask.sum()
)

print(
    "Null plan IDs:",
    subscriptions["plan_id"].isna().sum()
)


# ------------------------------------------------------------
# 4. Date parsing
# ------------------------------------------------------------

print("\n4. DATE VALIDATION")
print("-" * 50)

subscriptions["start_date_parsed"] = pd.to_datetime(
    subscriptions["start_date"],
    format="mixed",
    errors="coerce"
)

subscriptions["end_date_parsed"] = pd.to_datetime(
    subscriptions["end_date"],
    format="mixed",
    errors="coerce"
)

print(
    "Unparsed start dates:",
    subscriptions["start_date_parsed"].isna().sum()
)

print(
    "Unparsed end dates:",
    subscriptions["end_date_parsed"].isna().sum()
)

# ------------------------------------------------------------
# 4A. Future start date validation
# ------------------------------------------------------------

reference_date = pd.Timestamp("2026-08-15")

future_start_mask = (
    subscriptions["start_date_parsed"] > reference_date
)

print(
    "Future start dates:",
    future_start_mask.sum()
)

# ------------------------------------------------------------
# 5. End date before start date
# ------------------------------------------------------------

invalid_date_order = (
    subscriptions["end_date_parsed"].notna()
    &
    subscriptions["start_date_parsed"].notna()
    &
    (
        subscriptions["end_date_parsed"]
        <
        subscriptions["start_date_parsed"]
    )
)

print(
    "End date before start date:",
    invalid_date_order.sum()
)


# ------------------------------------------------------------
# 6. Subscription status
# ------------------------------------------------------------

print("\n6. SUBSCRIPTION STATUS")
print("-" * 50)

print(
    subscriptions["subscription_status"]
    .value_counts(dropna=False)
)

SUBSCRIPTIONS DATA QUALITY INVESTIGATION

1. BASIC INFORMATION
--------------------------------------------------
Rows: 20523
Unique subscription IDs: 20523
Duplicate subscription IDs: 0

2. MISSING VALUES
--------------------------------------------------
subscription_id            0
customer_id                0
plan_id                   41
start_date                 0
end_date               17017
billing_cycle              0
monthly_charge_inr         0
subscription_status        0
dtype: int64

3. PLAN ID VALIDATION
--------------------------------------------------
Invalid plan IDs: 41
Null plan IDs: 41

4. DATE VALIDATION
--------------------------------------------------
Unparsed start dates: 0
Unparsed end dates: 17017
Future start dates: 58
End date before start date: 162

6. SUBSCRIPTION STATUS
--------------------------------------------------
subscription_status
Active           16930
Terminated        3491
UNKNOWN_STATE      102
Name: count, dtype: int64


In [30]:
# ============================================================
# STEP 7E — CONTRACTS INVESTIGATION
# ============================================================

contracts = tables["contracts"].copy()

print("CONTRACTS DATA QUALITY INVESTIGATION")
print("=" * 90)

print("\n1. BASIC INFORMATION")
print("-" * 50)

print("Rows:", len(contracts))
print("Unique contract IDs:", contracts["contract_id"].nunique())
print(
    "Duplicate contract IDs:",
    contracts["contract_id"].duplicated().sum()
)


print("\n2. MISSING VALUES")
print("-" * 50)

print(
    contracts.isna().sum()
)


print("\n3. PLAN ID VALIDATION")
print("-" * 50)

invalid_contract_plans = ~(
    contracts["plan_id"]
    .astype(str)
    .isin(valid_plan_ids)
)

print(
    "Invalid plan IDs:",
    invalid_contract_plans.sum()
)

print(
    "Null plan IDs:",
    contracts["plan_id"].isna().sum()
)


print("\n4. DATE VALIDATION")
print("-" * 50)

contracts["start_date_parsed"] = pd.to_datetime(
    contracts["start_date"],
    format="mixed",
    errors="coerce"
)

contracts["end_date_parsed"] = pd.to_datetime(
    contracts["end_date"],
    format="mixed",
    errors="coerce"
)

print(
    "Unparsed start dates:",
    contracts["start_date_parsed"].isna().sum()
)

print(
    "Unparsed end dates:",
    contracts["end_date_parsed"].isna().sum()
)


invalid_contract_dates = (
    contracts["end_date_parsed"].notna()
    &
    contracts["start_date_parsed"].notna()
    &
    (
        contracts["end_date_parsed"]
        <
        contracts["start_date_parsed"]
    )
)

print(
    "End date before start date:",
    invalid_contract_dates.sum()
)


print("\n5. CONTRACT TYPE")
print("-" * 50)

print(
    contracts["contract_type"]
    .value_counts(dropna=False)
)


print("\n6. RENEWAL STATUS")
print("-" * 50)

print(
    contracts["renewal_status"]
    .value_counts(dropna=False)
)

CONTRACTS DATA QUALITY INVESTIGATION

1. BASIC INFORMATION
--------------------------------------------------
Rows: 10607
Unique contract IDs: 10607
Duplicate contract IDs: 0

2. MISSING VALUES
--------------------------------------------------
contract_id               0
customer_id               0
plan_id                   0
contract_type             0
contract_length_months    0
start_date                0
end_date                  0
auto_renew                0
renewal_status            0
dtype: int64

3. PLAN ID VALIDATION
--------------------------------------------------
Invalid plan IDs: 0
Null plan IDs: 0

4. DATE VALIDATION
--------------------------------------------------
Unparsed start dates: 0
Unparsed end dates: 0
End date before start date: 0

5. CONTRACT TYPE
--------------------------------------------------
contract_type
Postpaid Mobile    3753
Prepaid Mobile     2904
Fiber Broadband    2193
Enterprise          811
IoT Solutions       579
Smart Home          367
Name:

In [31]:
# ============================================================
# STEP 7E — PLAN HISTORY INVESTIGATION
# ============================================================

plan_history = tables["plan_history"].copy()

print("PLAN HISTORY DATA QUALITY INVESTIGATION")
print("=" * 90)

print("\n1. BASIC INFORMATION")
print("-" * 50)

print("Rows:", len(plan_history))
print("Unique history IDs:", plan_history["history_id"].nunique())

print(
    "Duplicate history IDs:",
    plan_history["history_id"].duplicated().sum()
)


print("\n2. MISSING VALUES")
print("-" * 50)

print(
    plan_history.isna().sum()
)


print("\n3. OLD PLAN VALIDATION")
print("-" * 50)

invalid_old_plan = ~(
    plan_history["old_plan_id"]
    .astype(str)
    .isin(valid_plan_ids)
)

print(
    "Invalid old plan IDs:",
    invalid_old_plan.sum()
)

print(
    "Null old plan IDs:",
    plan_history["old_plan_id"].isna().sum()
)


print("\n4. NEW PLAN VALIDATION")
print("-" * 50)

invalid_new_plan = ~(
    plan_history["new_plan_id"]
    .astype(str)
    .isin(valid_plan_ids)
)

print(
    "Invalid new plan IDs:",
    invalid_new_plan.sum()
)

print(
    "Null new plan IDs:",
    plan_history["new_plan_id"].isna().sum()
)


print("\n5. SAME OLD AND NEW PLAN")
print("-" * 50)

same_plan = (
    plan_history["old_plan_id"]
    ==
    plan_history["new_plan_id"]
)

print(
    "Records where old plan = new plan:",
    same_plan.sum()
)


print("\n6. CHANGE DATE")
print("-" * 50)

plan_history["change_date_parsed"] = pd.to_datetime(
    plan_history["change_date"],
    format="mixed",
    errors="coerce"
)

print(
    "Unparsed change dates:",
    plan_history["change_date_parsed"].isna().sum()
)

PLAN HISTORY DATA QUALITY INVESTIGATION

1. BASIC INFORMATION
--------------------------------------------------
Rows: 19349
Unique history IDs: 19349
Duplicate history IDs: 0

2. MISSING VALUES
--------------------------------------------------
history_id       0
customer_id      0
old_plan_id      0
new_plan_id      0
change_date      0
change_reason    0
dtype: int64

3. OLD PLAN VALIDATION
--------------------------------------------------
Invalid old plan IDs: 0
Null old plan IDs: 0

4. NEW PLAN VALIDATION
--------------------------------------------------
Invalid new plan IDs: 0
Null new plan IDs: 0

5. SAME OLD AND NEW PLAN
--------------------------------------------------
Records where old plan = new plan: 761

6. CHANGE DATE
--------------------------------------------------
Unparsed change dates: 0



--------------------------------------------------------------------
# Step 7E — Subscriptions, Contracts and Plan History Cleaning

Cleaning actions:

- Preserve valid active subscriptions with null end dates.
- Convert invalid/null subscription plan IDs to null.
- Convert UNKNOWN_STATE to null.
- Convert invalid subscription date ranges to null end dates.
- Preserve contracts because no data-quality issues were identified.
- Preserve plan history records where old and new plans are identical;
  these records are flagged as potentially redundant rather than deleted.
- The original CSV files remain unchanged.

In [32]:
# ============================================================
# STEP 7E — SUBSCRIPTIONS CLEANING
# ============================================================

subscriptions_clean = tables["subscriptions"].copy()

print("SUBSCRIPTIONS CLEANING")
print("=" * 80)

# ------------------------------------------------------------
# 1. Validate plan IDs
# ------------------------------------------------------------

valid_plan_ids = set(
    tables["plans"]["plan_id"]
    .dropna()
    .astype(str)
)

invalid_plan_mask = ~(
    subscriptions_clean["plan_id"]
    .astype(str)
    .isin(valid_plan_ids)
)

invalid_plan_count = invalid_plan_mask.sum()

subscriptions_clean.loc[
    invalid_plan_mask,
    "plan_id"
] = np.nan

print(
    "Invalid/null plan IDs converted to null:",
    invalid_plan_count
)


# ------------------------------------------------------------
# 2. Parse dates
# ------------------------------------------------------------

subscriptions_clean["start_date"] = pd.to_datetime(
    subscriptions_clean["start_date"],
    format="mixed",
    errors="coerce"
)

subscriptions_clean["end_date"] = pd.to_datetime(
    subscriptions_clean["end_date"],
    format="mixed",
    errors="coerce"
)

# ------------------------------------------------------------
# 3. Future subscription start dates → null
# ------------------------------------------------------------

reference_date = pd.Timestamp("2026-08-15")

future_start_mask = (
    subscriptions_clean["start_date"] > reference_date
)

future_start_count = future_start_mask.sum()

subscriptions_clean.loc[
    future_start_mask,
    "start_date"
] = pd.NaT

print(
    "Future subscription start dates corrected:",
    future_start_count
)

# ------------------------------------------------------------
# 4. Invalid date ranges
# ------------------------------------------------------------

invalid_date_mask = (
    subscriptions_clean["end_date"].notna()
    &
    subscriptions_clean["start_date"].notna()
    &
    (
        subscriptions_clean["end_date"]
        <
        subscriptions_clean["start_date"]
    )
)

invalid_date_count = invalid_date_mask.sum()

subscriptions_clean.loc[
    invalid_date_mask,
    "end_date"
] = pd.NaT

print(
    "Invalid end dates corrected:",
    invalid_date_count
)


# ------------------------------------------------------------
# 5. Invalid subscription status
# ------------------------------------------------------------

unknown_status_mask = (
    subscriptions_clean["subscription_status"]
    == "UNKNOWN_STATE"
)

unknown_status_count = unknown_status_mask.sum()

subscriptions_clean.loc[
    unknown_status_mask,
    "subscription_status"
] = np.nan

print(
    "UNKNOWN_STATE statuses converted to null:",
    unknown_status_count
)


# ------------------------------------------------------------
# 6. Final validation
# ------------------------------------------------------------

print("\nFINAL SUBSCRIPTION VALIDATION")
print("=" * 80)

print("Rows:", len(subscriptions_clean))
print(
    "Unique subscription IDs:",
    subscriptions_clean["subscription_id"].nunique()
)

print(
    "Null plan IDs:",
    subscriptions_clean["plan_id"].isna().sum()
)
print(
    "Null start dates:",
    subscriptions_clean["start_date"].isna().sum()
)

print(
    "Null end dates:",
    subscriptions_clean["end_date"].isna().sum()
)

print(
    "Null subscription statuses:",
    subscriptions_clean["subscription_status"].isna().sum()
)

SUBSCRIPTIONS CLEANING
Invalid/null plan IDs converted to null: 41
Future subscription start dates corrected: 58
Invalid end dates corrected: 148
UNKNOWN_STATE statuses converted to null: 102

FINAL SUBSCRIPTION VALIDATION
Rows: 20523
Unique subscription IDs: 20523
Null plan IDs: 41
Null start dates: 58
Null end dates: 17165
Null subscription statuses: 102


In [33]:
# ============================================================
# SAVE CLEANED SUBSCRIPTIONS DATA
# ============================================================

subscriptions_clean.to_csv(
    "cleaned_data/subscriptions_clean.csv",
    index=False
)

print("Cleaned subscriptions data saved successfully.")
print("File: cleaned_data/subscriptions_clean.csv")
print("Rows:", len(subscriptions_clean))
print("Columns:", len(subscriptions_clean.columns))

Cleaned subscriptions data saved successfully.
File: cleaned_data/subscriptions_clean.csv
Rows: 20523
Columns: 8


In [34]:
# Verify saved subscriptions CSV

subscriptions_check = pd.read_csv(
    "cleaned_data/subscriptions_clean.csv"
)

print("SUBSCRIPTIONS CLEAN CSV VALIDATION")
print("=" * 80)
print("Rows:", len(subscriptions_check))
print("Columns:", len(subscriptions_check.columns))
print(
    "Unique subscription IDs:",
    subscriptions_check["subscription_id"].nunique()
)

SUBSCRIPTIONS CLEAN CSV VALIDATION
Rows: 20523
Columns: 8
Unique subscription IDs: 20523


In [35]:
# ============================================================
# STEP 7E — CONTRACTS CLEANING
# ============================================================

contracts_clean = tables["contracts"].copy()

print("CONTRACTS CLEANING")
print("=" * 80)

# Parse dates consistently
contracts_clean["start_date"] = pd.to_datetime(
    contracts_clean["start_date"],
    format="mixed",
    errors="coerce"
)

contracts_clean["end_date"] = pd.to_datetime(
    contracts_clean["end_date"],
    format="mixed",
    errors="coerce"
)

print("No structural cleaning required.")

print("\nFINAL CONTRACT VALIDATION")
print("=" * 80)

print("Rows:", len(contracts_clean))
print(
    "Unique contract IDs:",
    contracts_clean["contract_id"].nunique()
)

print(
    "Null plan IDs:",
    contracts_clean["plan_id"].isna().sum()
)

CONTRACTS CLEANING
No structural cleaning required.

FINAL CONTRACT VALIDATION
Rows: 10607
Unique contract IDs: 10607
Null plan IDs: 0


In [36]:
# ============================================================
# STEP 7E — PLAN HISTORY CLEANING
# ============================================================

plan_history_clean = tables["plan_history"].copy()

print("PLAN HISTORY CLEANING")
print("=" * 80)

# Parse change date
plan_history_clean["change_date"] = pd.to_datetime(
    plan_history_clean["change_date"],
    format="mixed",
    errors="coerce"
)

# Flag potentially redundant changes
plan_history_clean["same_plan_flag"] = (
    plan_history_clean["old_plan_id"]
    ==
    plan_history_clean["new_plan_id"]
)

same_plan_count = plan_history_clean["same_plan_flag"].sum()

print(
    "Records where old plan = new plan:",
    same_plan_count
)

print(
    "These records are retained and flagged for investigation."
)

print("\nFINAL PLAN HISTORY VALIDATION")
print("=" * 80)

print("Rows:", len(plan_history_clean))
print(
    "Unique history IDs:",
    plan_history_clean["history_id"].nunique()
)

print(
    "Unparsed change dates:",
    plan_history_clean["change_date"].isna().sum()
)

##Saving Cleaned data
plan_history_clean.to_csv(
    "cleaned_data/plan_history_clean.csv",
    index=False
)
print("\nSaving PLAN HISTORY data to CSV")
print("=" * 80)

print("Cleaned plan history data saved successfully.")
print("File: cleaned_data/plan_history_clean.csv")
print("Rows:", len(plan_history_clean))
print("Columns:", len(plan_history_clean.columns))


PLAN HISTORY CLEANING
Records where old plan = new plan: 761
These records are retained and flagged for investigation.

FINAL PLAN HISTORY VALIDATION
Rows: 19349
Unique history IDs: 19349
Unparsed change dates: 0

Saving PLAN HISTORY data to CSV
Cleaned plan history data saved successfully.
File: cleaned_data/plan_history_clean.csv
Rows: 19349
Columns: 7


------------------------------------------------------------------------------------------
# Step 7F — Usage Data Quality Investigation

The data-quality issue log identifies 171 outlier values in usage_data.

The usage_sms, usage_voice and network_quality tables have no reported
data-quality issues and therefore require no corrective cleaning at this stage.

The usage_data outliers will be investigated before deciding whether they
should be corrected, capped, or retained.

In [37]:
# ============================================================
# STEP 7F — USAGE DATA OUTLIER INVESTIGATION
# ============================================================

usage = tables["usage_data"].copy()

print("USAGE DATA OUTLIER INVESTIGATION")
print("=" * 80)

print("\n1. BASIC VALIDATION")
print("-" * 50)

print("Rows:", len(usage))
print("Unique usage IDs:", usage["usage_id"].nunique())
print(
    "Duplicate usage IDs:",
    usage["usage_id"].duplicated().sum()
)

print("\n2. MISSING VALUES")
print("-" * 50)

print(usage.isna().sum())

print("\n3. NUMERIC SUMMARY")
print("-" * 50)

print(
    usage[
        ["data_gb_used", "data_sessions"]
    ].describe()
)

print("\n4. POTENTIAL OUTLIERS — DATA USAGE")
print("-" * 50)

Q1 = usage["data_gb_used"].quantile(0.25)
Q3 = usage["data_gb_used"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_mask = (
    (usage["data_gb_used"] < lower_bound)
    |
    (usage["data_gb_used"] > upper_bound)
)

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Potential outliers:", outlier_mask.sum())

print("\nOUTLIER SAMPLE")
print("-" * 50)

print(
    usage.loc[
        outlier_mask,
        [
            "usage_id",
            "customer_id",
            "usage_month",
            "data_gb_used",
            "data_sessions"
        ]
    ].head(30).to_string(index=False)
)

USAGE DATA OUTLIER INVESTIGATION

1. BASIC VALIDATION
--------------------------------------------------
Rows: 57000
Unique usage IDs: 57000
Duplicate usage IDs: 0

2. MISSING VALUES
--------------------------------------------------
usage_id         0
customer_id      0
usage_month      0
data_gb_used     0
data_sessions    0
dtype: int64

3. NUMERIC SUMMARY
--------------------------------------------------
       data_gb_used  data_sessions
count  57000.000000   57000.000000
mean      40.184885     610.115053
std      332.574130     341.278399
min        0.240000      20.000000
25%       11.390000     314.000000
50%       19.140000     608.000000
75%       32.630000     907.000000
max    22172.700708    1199.000000

4. POTENTIAL OUTLIERS — DATA USAGE
--------------------------------------------------
Q1: 11.39
Q3: 32.63
IQR: 21.240000000000002
Lower bound: -20.470000000000002
Upper bound: 64.49000000000001
Potential outliers: 4480

OUTLIER SAMPLE
------------------------------------

In [38]:
# ============================================================
# STEP 7F — IDENTIFY EXTREME USAGE OUTLIERS
# ============================================================

usage = tables["usage_data"].copy()

print("EXTREME USAGE VALUE INVESTIGATION")
print("=" * 80)

# Sort by data usage from highest to lowest
extreme_usage = usage.sort_values(
    "data_gb_used",
    ascending=False
)

print("\nTOP 30 HIGHEST DATA USAGE VALUES")
print("-" * 60)

print(
    extreme_usage[
        [
            "usage_id",
            "customer_id",
            "usage_month",
            "data_gb_used",
            "data_sessions"
        ]
    ].head(30).to_string(index=False)
)

print("\nUSAGE VALUES ABOVE 500 GB")
print("-" * 60)

above_500 = usage[
    usage["data_gb_used"] > 500
]

print(
    "Records above 500 GB:",
    len(above_500)
)

print(
    above_500[
        [
            "usage_id",
            "customer_id",
            "usage_month",
            "data_gb_used",
            "data_sessions"
        ]
    ].to_string(index=False)
)

EXTREME USAGE VALUE INVESTIGATION

TOP 30 HIGHEST DATA USAGE VALUES
------------------------------------------------------------
  usage_id customer_id usage_month  data_gb_used  data_sessions
UD00015078    C0005026     01-2026  22172.700708             31
UD00023090    C0007697     02-2026  21960.635745            489
UD00010055    C0003352     02-2026  18348.446462            369
UD00034860    C0011620     01-2026  17377.228312            765
UD00026593    C0008865     03-2026  15322.701632            268
UD00029838    C0009946     01-2026  13886.727541           1105
UD00053992    C0017998     03-2026  13344.522727            862
UD00056097    C0018699     01-2026  13154.906387            317
UD00045209    C0015070     02-2026  12747.455634            929
UD00019930    C0006644     03-2026  12581.380386            496
UD00023271    C0007757     01-2026  12277.077821           1169
UD00039699    C0013233     01-2026  11930.873657           1199
UD00054375    C0018125     01-2026  116

## Usage Data Quality Decision

The usage_data table contains 57,000 records with no missing values or duplicate usage IDs.

An IQR-based analysis identified 4,480 statistical outliers in `data_gb_used`. However, statistical outliers are not automatically data errors and may represent genuinely high-usage customers.

Further investigation identified 166 records with data usage above 500 GB, including several extremely large values. The project's `data_quality_issue_log` identifies 171 affected rows as usage-data outliers.

Therefore, the cleaning process will focus on the 171 documented data-quality outliers rather than removing all 4,480 statistical outliers.

Outlier records will be handled carefully to avoid distorting genuine customer usage behavior and downstream churn analysis.

In [39]:
# ================================================================
# USAGE DATA CLEANING — STEP 7F
# ================================================================

usage_clean =  tables["usage_data"].copy()


print("=" * 80)
print("USAGE DATA CLEANING")
print("=" * 80)

# ------------------------------------------------
# 1. Basic validation
# ------------------------------------------------

print(f"Original rows: {len(usage_clean)}")
print(f"Duplicate usage IDs: {usage_clean['usage_id'].duplicated().sum()}")
print(f"Missing values: {usage_clean.isnull().sum().sum()}")

# ------------------------------------------------
# 2. Identify extreme usage values
# ------------------------------------------------

extreme_usage = usage_clean[
    usage_clean["data_gb_used"] > 500
].copy()

print("\n" + "-" * 80)
print("EXTREME USAGE VALUES (>500 GB)")
print("-" * 80)

print(f"Records above 500 GB: {len(extreme_usage)}")

# ------------------------------------------------
# 3. Display highest usage records
# ------------------------------------------------

print("\nTOP 20 HIGHEST USAGE RECORDS")
print("-" * 80)

print(
    extreme_usage[
        ["usage_id", "customer_id", "usage_month",
         "data_gb_used", "data_sessions"]
    ]
    .sort_values("data_gb_used", ascending=False)
    .head(20)
    .to_string(index=False)
)

# ------------------------------------------------
# 4. Check documented data-quality count
# ------------------------------------------------

documented_outliers = 171

print("\n" + "-" * 80)
print("DOCUMENTED DATA-QUALITY CHECK")
print("-" * 80)

print(f"Documented usage-data outliers: {documented_outliers}")
print(f"Currently identified >500 GB records: {len(extreme_usage)}")
print(
    f"Difference: "
    f"{documented_outliers - len(extreme_usage)}"
)

# ------------------------------------------------
# 5. Do NOT delete records yet
# ------------------------------------------------

print("\n" + "-" * 80)
print("CLEANING DECISION")
print("-" * 80)

print("No usage records have been deleted or modified yet.")
print("The extreme values will be investigated before cleaning.")

USAGE DATA CLEANING
Original rows: 57000
Duplicate usage IDs: 0
Missing values: 0

--------------------------------------------------------------------------------
EXTREME USAGE VALUES (>500 GB)
--------------------------------------------------------------------------------
Records above 500 GB: 166

TOP 20 HIGHEST USAGE RECORDS
--------------------------------------------------------------------------------
  usage_id customer_id usage_month  data_gb_used  data_sessions
UD00015078    C0005026     01-2026  22172.700708             31
UD00023090    C0007697     02-2026  21960.635745            489
UD00010055    C0003352     02-2026  18348.446462            369
UD00034860    C0011620     01-2026  17377.228312            765
UD00026593    C0008865     03-2026  15322.701632            268
UD00029838    C0009946     01-2026  13886.727541           1105
UD00053992    C0017998     03-2026  13344.522727            862
UD00056097    C0018699     01-2026  13154.906387            317
UD00045209 

In [40]:
# ================================================================
# FIND THE DOCUMENTED 171 USAGE OUTLIERS
# ================================================================

print("=" * 80)
print("USAGE OUTLIER THRESHOLD INVESTIGATION")
print("=" * 80)

# Different possible thresholds
thresholds = [100, 150, 200, 250, 300, 350, 400, 450, 500]

print("\nRecords above different data usage thresholds:")
print("-" * 60)

for threshold in thresholds:
    count = (usage_clean["data_gb_used"] > threshold).sum()
    print(f"> {threshold:>3} GB : {count:>5} records")

# ------------------------------------------------
# Check values around the 171st highest record
# ------------------------------------------------

sorted_usage = usage_clean.sort_values(
    "data_gb_used",
    ascending=False
).reset_index(drop=True)

print("\n" + "-" * 80)
print("VALUES AROUND THE 171st HIGHEST RECORD")
print("-" * 80)

print(
    sorted_usage[
        ["usage_id", "customer_id", "usage_month",
         "data_gb_used", "data_sessions"]
    ].iloc[165:176].to_string(index=False)
)

# ------------------------------------------------
# Exact count at the 171st position
# ------------------------------------------------

threshold_171 = sorted_usage.loc[170, "data_gb_used"]

print("\n" + "-" * 80)
print(f"171st highest data usage value: {threshold_171}")
print("-" * 80)

print(
    f"Records with data_gb_used >= {threshold_171}: "
    f"{(usage_clean['data_gb_used'] >= threshold_171).sum()}"
)

USAGE OUTLIER THRESHOLD INVESTIGATION

Records above different data usage thresholds:
------------------------------------------------------------
> 100 GB :  1556 records
> 150 GB :   468 records
> 200 GB :   234 records
> 250 GB :   187 records
> 300 GB :   173 records
> 350 GB :   171 records
> 400 GB :   168 records
> 450 GB :   167 records
> 500 GB :   166 records

--------------------------------------------------------------------------------
VALUES AROUND THE 171st HIGHEST RECORD
--------------------------------------------------------------------------------
  usage_id customer_id usage_month  data_gb_used  data_sessions
UD00035821    C0011941     03-2026    544.661710            925
UD00046581    C0015527     01-2026    497.511359            647
UD00001723    C0000575     03-2026    437.824105            769
UD00040764    C0013588     01-2026    371.730000            235
UD00006298    C0002100     03-2026    369.990918            580
UD00046458    C0015486     01-2026    356.

---------------------------------
USAGE DATA OUTLIER DECISION
================================================================================

Total usage records: 57,000

Documented data-quality outliers: 171

Outlier threshold identified: >= 356.54 GB

Records meeting threshold: 171

Decision:
The 171 high-usage records will NOT be deleted.
They will be retained because they may represent genuine
high-usage customers.

The records will be flagged as potential outliers for
analysis and further investigation.

Cleaning action:
No usage values were modified.
No usage records were deleted.
-------------------------------------------------------------------------

In [41]:
# Create a clean copy
usage_data_clean =tables["usage_data"].copy()

# Flag potential outliers
usage_data_clean["usage_outlier_flag"] = (
    usage_data_clean["data_gb_used"] >= 356.54
)

# Validate
print("USAGE OUTLIER FLAGGING")
print("=" * 80)

print("Total rows:", len(usage_data_clean))
print(
    "Potential outliers:",
    usage_data_clean["usage_outlier_flag"].sum()
)
print(
    "Normal records:",
    (~usage_data_clean["usage_outlier_flag"]).sum()
)

USAGE OUTLIER FLAGGING
Total rows: 57000
Potential outliers: 171
Normal records: 56829


In [42]:
# Save cleaned usage data for Phase 2 EDA

usage_data_clean.to_csv(
    "cleaned_data/usage_data_clean.csv",
    index=False
)

print("Saved: cleaned_data/usage_data_clean.csv")

Saved: cleaned_data/usage_data_clean.csv


----------------------------------------------------------------
Step 7E — Remaining Usage Tables

We'll clean and validate in this order:

usage_sms
usage_voice
network_quality


## 7F.1 — Usage SMS Initial Inspection

The `usage_sms` table was inspected for its structure, data types, missing values, and duplicate records.

### Initial Findings
- Total records: **57,000**
- Total columns: **5**
- Columns: `usage_id`, `customer_id`, `usage_month`, `sms_sent`, `sms_received`
- No missing values were found.
- No duplicate rows were found.
- `sms_sent` and `sms_received` are stored as integer values.
- `usage_month` is stored as a string in `MM-YYYY` format.

The table was then subjected to further validation checks.

In [43]:
# ============================================================
# STEP 7F.1 — USAGE SMS INITIAL INSPECTION
# ============================================================

sms = tables["usage_sms"]

print("=" * 70)
print("USAGE SMS — INITIAL INSPECTION")
print("=" * 70)

print("\nShape:")
print(sms.shape)

print("\nColumns:")
print(sms.columns.tolist())

print("\nData Types:")
print(sms.dtypes)

print("\nFirst 5 Rows:")
display(sms.head())

print("\nMissing Values:")
print(sms.isnull().sum())

print("\nDuplicate Rows:")
print(sms.duplicated().sum())

USAGE SMS — INITIAL INSPECTION

Shape:
(57000, 5)

Columns:
['usage_id', 'customer_id', 'usage_month', 'sms_sent', 'sms_received']

Data Types:
usage_id          str
customer_id       str
usage_month       str
sms_sent        int64
sms_received    int64
dtype: object

First 5 Rows:


,usage_id,customer_id,usage_month,sms_sent,sms_received
0,US00000001,C0000001,03-2026,19,20
1,US00000002,C0000001,02-2026,32,18
2,US00000003,C0000001,01-2026,21,28
3,US00000004,C0000002,03-2026,15,24
4,US00000005,C0000002,02-2026,23,33



Missing Values:
usage_id        0
customer_id     0
usage_month     0
sms_sent        0
sms_received    0
dtype: int64

Duplicate Rows:
0


--------------------------------------------
## 7F.2 — Usage SMS Validation

The `usage_sms` table was validated for identifier uniqueness, monthly distribution, SMS usage ranges, and invalid negative values.

### Validation Findings
- `usage_id` contains **57,000 unique values**, matching the total number of records.
- There are **19,000 unique customers**.
- The table contains three usage months:
  - **01-2026:** 19,000 records
  - **02-2026:** 19,000 records
  - **03-2026:** 19,000 records
- `sms_sent` ranges from **3 to 61**.
- `sms_received` ranges from **5 to 48**.
- No negative `sms_sent` values were found.
- No negative `sms_received` values were found.

The results indicate that the SMS usage values are structurally valid.

In [44]:
# ============================================================
# STEP 7F.2 — USAGE SMS VALIDATION
# ============================================================

print("=" * 70)
print("USAGE SMS — VALIDATION")
print("=" * 70)

print("\nUnique usage_id:")
print(sms["usage_id"].nunique())

print("\nUnique customer_id:")
print(sms["customer_id"].nunique())

print("\nUsage months:")
print(sms["usage_month"].value_counts().sort_index())

print("\nSMS Sent — Summary:")
print(sms["sms_sent"].describe())

print("\nSMS Received — Summary:")
print(sms["sms_received"].describe())

print("\nNegative SMS Sent:")
print((sms["sms_sent"] < 0).sum())

print("\nNegative SMS Received:")
print((sms["sms_received"] < 0).sum())

USAGE SMS — VALIDATION

Unique usage_id:
57000

Unique customer_id:
19000

Usage months:
usage_month
01-2026    19000
02-2026    19000
03-2026    19000
Name: count, dtype: int64

SMS Sent — Summary:
count    57000.000000
mean        22.426281
std          8.826579
min          3.000000
25%         16.000000
50%         20.000000
75%         27.000000
max         61.000000
Name: sms_sent, dtype: float64

SMS Received — Summary:
count    57000.000000
mean        25.003211
std          5.017677
min          5.000000
25%         22.000000
50%         25.000000
75%         28.000000
max         48.000000
Name: sms_received, dtype: float64

Negative SMS Sent:
0

Negative SMS Received:
0


--------------------------------------------------------
## 7F.3 — Customer/Month Completeness Check

A customer-month completeness check was performed to verify that each customer has usage records for all three months.

### Results
- Customers with exactly 3 months: **19,000**
- Customers with fewer than 3 months: **0**
- Customers with more than 3 months: **0**

### Conclusion
Every customer has exactly one usage record for each of the three months.

Therefore, the `usage_sms` table is considered **CLEAN** and requires no data cleaning.

In [45]:
# ============================================================
# STEP 7F.3 — CUSTOMER / MONTH COMPLETENESS CHECK
# ============================================================

customer_month_counts = (
    sms.groupby("customer_id")["usage_month"]
    .nunique()
)

print("=" * 70)
print("USAGE SMS — CUSTOMER/MONTH COMPLETENESS")
print("=" * 70)

print("\nCustomers with exactly 3 months:")
print((customer_month_counts == 3).sum())

print("\nCustomers with fewer than 3 months:")
print((customer_month_counts < 3).sum())

print("\nCustomers with more than 3 months:")
print((customer_month_counts > 3).sum())

USAGE SMS — CUSTOMER/MONTH COMPLETENESS

Customers with exactly 3 months:
19000

Customers with fewer than 3 months:
0

Customers with more than 3 months:
0


-----------------------------------------------------------------------
## 7F.4 — Usage Voice Initial Inspection

The `usage_voice` table was inspected for its structure, data types, missing values, and duplicate records.

### Initial Findings
- Total records: **57,000**
- Total columns: **6**
- Columns: `usage_id`, `customer_id`, `usage_month`, `voice_minutes_used`, `outgoing_calls`, `incoming_calls`
- No missing values were found.
- No duplicate rows were found.
- `voice_minutes_used`, `outgoing_calls`, and `incoming_calls` are stored as integer values.
- `usage_month` is stored as a string in `MM-YYYY` format.

The table requires further validation of identifier uniqueness, monthly distribution, usage ranges, and negative values before determining whether any cleaning is required.

In [46]:
# ============================================================
# STEP 7F.4 — USAGE VOICE INITIAL INSPECTION
# ============================================================

voice = tables["usage_voice"]

print("=" * 70)
print("USAGE VOICE — INITIAL INSPECTION")
print("=" * 70)

print("\nShape:")
print(voice.shape)

print("\nColumns:")
print(voice.columns.tolist())

print("\nData Types:")
print(voice.dtypes)

print("\nFirst 5 Rows:")
display(voice.head())

print("\nMissing Values:")
print(voice.isnull().sum())

print("\nDuplicate Rows:")
print(voice.duplicated().sum())

USAGE VOICE — INITIAL INSPECTION

Shape:
(57000, 6)

Columns:
['usage_id', 'customer_id', 'usage_month', 'voice_minutes_used', 'outgoing_calls', 'incoming_calls']

Data Types:
usage_id                str
customer_id             str
usage_month             str
voice_minutes_used    int64
outgoing_calls        int64
incoming_calls        int64
dtype: object

First 5 Rows:


,usage_id,customer_id,usage_month,voice_minutes_used,outgoing_calls,incoming_calls
0,UV00000001,C0000001,03-2026,439,356,255
1,UV00000002,C0000001,02-2026,705,32,694
2,UV00000003,C0000001,01-2026,206,339,194
3,UV00000004,C0000002,03-2026,133,485,432
4,UV00000005,C0000002,02-2026,208,501,84



Missing Values:
usage_id              0
customer_id           0
usage_month           0
voice_minutes_used    0
outgoing_calls        0
incoming_calls        0
dtype: int64

Duplicate Rows:
0


In [47]:
# ============================================================
# STEP 7F.5 — USAGE VOICE VALIDATION
# ============================================================

print("=" * 70)
print("USAGE VOICE — VALIDATION")
print("=" * 70)

print("\nUnique usage_id:")
print(voice["usage_id"].nunique())

print("\nUnique customer_id:")
print(voice["customer_id"].nunique())

print("\nUsage months:")
print(voice["usage_month"].value_counts().sort_index())

print("\nVoice Minutes Used — Summary:")
print(voice["voice_minutes_used"].describe())

print("\nOutgoing Calls — Summary:")
print(voice["outgoing_calls"].describe())

print("\nIncoming Calls — Summary:")
print(voice["incoming_calls"].describe())

print("\nNegative Voice Minutes:")
print((voice["voice_minutes_used"] < 0).sum())

print("\nNegative Outgoing Calls:")
print((voice["outgoing_calls"] < 0).sum())

print("\nNegative Incoming Calls:")
print((voice["incoming_calls"] < 0).sum())

USAGE VOICE — VALIDATION

Unique usage_id:
57000

Unique customer_id:
19000

Usage months:
usage_month
01-2026    19000
02-2026    19000
03-2026    19000
Name: count, dtype: int64

Voice Minutes Used — Summary:
count    57000.000000
mean       224.918947
std        165.811242
min          0.000000
25%        105.000000
50%        185.000000
75%        301.000000
max       1588.000000
Name: voice_minutes_used, dtype: float64

Outgoing Calls — Summary:
count    57000.000000
mean       301.884439
std        171.686178
min          5.000000
25%        154.000000
50%        302.000000
75%        451.000000
max        599.000000
Name: outgoing_calls, dtype: float64

Incoming Calls — Summary:
count    57000.000000
mean       352.015877
std        200.581056
min          5.000000
25%        179.000000
50%        352.000000
75%        526.000000
max        699.000000
Name: incoming_calls, dtype: float64

Negative Voice Minutes:
0

Negative Outgoing Calls:
0

Negative Incoming Calls:
0


---------------------------------------
## 7F.5 — Usage Voice Validation

The `usage_voice` table was validated for identifier uniqueness, monthly distribution, usage ranges, and invalid negative values.

### Validation Findings
- `usage_id` contains **57,000 unique values**, matching the total number of records.
- There are **19,000 unique customers**.
- The table contains three usage months:
  - **01-2026:** 19,000 records
  - **02-2026:** 19,000 records
  - **03-2026:** 19,000 records
- `voice_minutes_used` ranges from **0 to 1,588 minutes**.
- `outgoing_calls` ranges from **5 to 599 calls**.
- `incoming_calls` ranges from **5 to 699 calls**.
- No negative `voice_minutes_used` values were found.
- No negative `outgoing_calls` values were found.
- No negative `incoming_calls` values were found.

The results indicate that the voice usage values are structurally valid. A customer-month completeness check was performed as the final validation step.

In [48]:
# ============================================================
# STEP 7F.6 — CUSTOMER / MONTH COMPLETENESS CHECK
# ============================================================

customer_month_counts = (
    voice.groupby("customer_id")["usage_month"]
    .nunique()
)

print("=" * 70)
print("USAGE VOICE — CUSTOMER/MONTH COMPLETENESS")
print("=" * 70)

print("\nCustomers with exactly 3 months:")
print((customer_month_counts == 3).sum())

print("\nCustomers with fewer than 3 months:")
print((customer_month_counts < 3).sum())

print("\nCustomers with more than 3 months:")
print((customer_month_counts > 3).sum())

USAGE VOICE — CUSTOMER/MONTH COMPLETENESS

Customers with exactly 3 months:
19000

Customers with fewer than 3 months:
0

Customers with more than 3 months:
0


-------------------------------
## 7F.6 — Customer/Month Completeness Check

A customer-month completeness check was performed to verify that each customer has voice usage records for all three months.

### Results
- Customers with exactly 3 months: **19,000**
- Customers with fewer than 3 months: **0**
- Customers with more than 3 months: **0**

### Conclusion
Every customer has exactly one voice usage record for each of the three months.

Therefore, the `usage_voice` table is considered **CLEAN** and requires no data cleaning.

In [49]:
# ============================================================
# STEP 7F.7 — NETWORK QUALITY INITIAL INSPECTION
# ============================================================

network = tables["network_quality"]

print("=" * 70)
print("NETWORK QUALITY — INITIAL INSPECTION")
print("=" * 70)

print("\nShape:")
print(network.shape)

print("\nColumns:")
print(network.columns.tolist())

print("\nData Types:")
print(network.dtypes)

print("\nFirst 5 Rows:")
display(network.head())

print("\nMissing Values:")
print(network.isnull().sum())

print("\nDuplicate Rows:")
print(network.duplicated().sum())

NETWORK QUALITY — INITIAL INSPECTION

Shape:
(57000, 8)

Columns:
['record_id', 'customer_id', 'city_id', 'month', 'avg_signal_strength_dbm', 'dropped_call_rate_pct', 'avg_download_speed_mbps', 'network_downtime_hours']

Data Types:
record_id                      str
customer_id                    str
city_id                        str
month                          str
avg_signal_strength_dbm    float64
dropped_call_rate_pct      float64
avg_download_speed_mbps    float64
network_downtime_hours     float64
dtype: object

First 5 Rows:


,record_id,customer_id,city_id,month,avg_signal_strength_dbm,dropped_call_rate_pct,avg_download_speed_mbps,network_downtime_hours
0,NQ00000001,C0000001,CT0026,03-2026,-74.3,3.15,25.1,0.87
1,NQ00000002,C0000001,CT0026,02-2026,-74.3,3.39,64.9,0.13
2,NQ00000003,C0000001,CT0026,01-2026,-74.3,1.75,68.7,0.46
3,NQ00000004,C0000002,CT0009,03-2026,-69.9,2.92,73.1,0.17
4,NQ00000005,C0000002,CT0009,02-2026,-69.9,3.02,75.3,0.33



Missing Values:
record_id                  0
customer_id                0
city_id                    0
month                      0
avg_signal_strength_dbm    0
dropped_call_rate_pct      0
avg_download_speed_mbps    0
network_downtime_hours     0
dtype: int64

Duplicate Rows:
0


--------------------------------
## 7F.7 — Network Quality Initial Inspection

The `network_quality` table was inspected for its structure, data types, missing values, and duplicate records.

### Initial Findings
- Total records: **57,000**
- Total columns: **8**
- Columns:
  - `record_id`
  - `customer_id`
  - `city_id`
  - `month`
  - `avg_signal_strength_dbm`
  - `dropped_call_rate_pct`
  - `avg_download_speed_mbps`
  - `network_downtime_hours`
- No missing values were found.
- No duplicate rows were found.
- `record_id`, `customer_id`, `city_id`, and `month` are stored as strings.
- Network performance metrics are stored as floating-point values.
- `month` is stored as a string in `MM-YYYY` format.

The table requires further validation of identifier uniqueness, monthly distribution, network metric ranges, and invalid values before determining whether any cleaning is required.

In [50]:
# ============================================================
# STEP 7F.8 — NETWORK QUALITY VALIDATION
# ============================================================

print("=" * 70)
print("NETWORK QUALITY — VALIDATION")
print("=" * 70)

print("\nUnique record_id:")
print(network["record_id"].nunique())

print("\nUnique customer_id:")
print(network["customer_id"].nunique())

print("\nUnique city_id:")
print(network["city_id"].nunique())

print("\nMonths:")
print(network["month"].value_counts().sort_index())

print("\nSignal Strength — Summary:")
print(network["avg_signal_strength_dbm"].describe())

print("\nDropped Call Rate — Summary:")
print(network["dropped_call_rate_pct"].describe())

print("\nDownload Speed — Summary:")
print(network["avg_download_speed_mbps"].describe())

print("\nNetwork Downtime — Summary:")
print(network["network_downtime_hours"].describe())

print("\nNegative Dropped Call Rate:")
print((network["dropped_call_rate_pct"] < 0).sum())

print("\nNegative Download Speed:")
print((network["avg_download_speed_mbps"] < 0).sum())

print("\nNegative Network Downtime:")
print((network["network_downtime_hours"] < 0).sum())

NETWORK QUALITY — VALIDATION

Unique record_id:
57000

Unique customer_id:
19000

Unique city_id:
68

Months:
month
01-2026    19000
02-2026    19000
03-2026    19000
Name: count, dtype: int64

Signal Strength — Summary:
count    57000.000000
mean       -67.992047
std          7.844086
min       -103.300000
25%        -73.300000
50%        -68.000000
75%        -62.600000
max        -50.600000
Name: avg_signal_strength_dbm, dtype: float64

Dropped Call Rate — Summary:
count    57000.000000
mean         2.401331
std          1.291287
min          0.040000
25%          1.460000
50%          2.230000
75%          3.180000
max          9.820000
Name: dropped_call_rate_pct, dtype: float64

Download Speed — Summary:
count    57000.000000
mean        49.058240
std         22.530991
min          4.400000
25%         30.300000
50%         47.300000
75%         65.500000
max        118.700000
Name: avg_download_speed_mbps, dtype: float64

Network Downtime — Summary:
count    57000.000000
mean   

------------------------------------------------------
## 7F.8 — Network Quality Validation

The `network_quality` table was validated for identifier uniqueness, monthly distribution, network metric ranges, and invalid negative values.

### Validation Findings
- `record_id` contains **57,000 unique values**, matching the total number of records.
- There are **19,000 unique customers**.
- There are **68 unique cities**.
- The table contains three months:
  - **01-2026:** 19,000 records
  - **02-2026:** 19,000 records
  - **03-2026:** 19,000 records
- `avg_signal_strength_dbm` ranges from **-103.3 to -50.6 dBm**.
- `dropped_call_rate_pct` ranges from **0.04% to 9.82%**.
- `avg_download_speed_mbps` ranges from **4.4 to 118.7 Mbps**.
- `network_downtime_hours` ranges from **0 to 6.96 hours**.
- No negative dropped call rates were found.
- No negative download speeds were found.
- No negative network downtime values were found.

The results indicate that the network quality metrics are within valid observed ranges. A customer-month completeness check was performed as the final validation step.

In [51]:
# ============================================================
# STEP 7F.9 — CUSTOMER / MONTH COMPLETENESS CHECK
# ============================================================

customer_month_counts = (
    network.groupby("customer_id")["month"]
    .nunique()
)

print("=" * 70)
print("NETWORK QUALITY — CUSTOMER/MONTH COMPLETENESS")
print("=" * 70)

print("\nCustomers with exactly 3 months:")
print((customer_month_counts == 3).sum())

print("\nCustomers with fewer than 3 months:")
print((customer_month_counts < 3).sum())

print("\nCustomers with more than 3 months:")
print((customer_month_counts > 3).sum())

NETWORK QUALITY — CUSTOMER/MONTH COMPLETENESS

Customers with exactly 3 months:
19000

Customers with fewer than 3 months:
0

Customers with more than 3 months:
0


-----------------------------------------------------
## 7F.9 — Customer/Month Completeness Check

A customer-month completeness check was performed to verify that each customer has network quality records for all three months.

### Results
- Customers with exactly 3 months: **19,000**
- Customers with fewer than 3 months: **0**
- Customers with more than 3 months: **0**

### Conclusion
Every customer has exactly one network quality record for each of the three months.

Therefore, the `network_quality` table is considered **CLEAN** and requires no data cleaning.

======================================
## Step 7G — Complaints Data Quality Investigation

The complaints table will be investigated for duplicate records, missing values, invalid customer references, and complaint status consistency.

The purpose of this investigation is to determine whether the complaints data is reliable for calculating the **number of unresolved complaints per customer**, which will later be used in Phase 2 to analyze the relationship between unresolved complaints and customer churn.

**Cleaning principle:** Preserve legitimate complaint history wherever possible. Only clearly invalid or duplicate records/fields will be corrected or removed based on the investigation findings.


In [52]:
# ============================================================
# STEP 7G — COMPLAINTS DATA QUALITY INVESTIGATION
# ============================================================

complaints = tables["complaints"].copy()

print("COMPLAINTS DATA QUALITY INVESTIGATION")
print("=" * 90)

# ------------------------------------------------------------
# 1. Basic information
# ------------------------------------------------------------

print("\n1. BASIC INFORMATION")
print("-" * 50)

print("Rows:", len(complaints))

print("Columns:")
print(complaints.columns.tolist())


# ------------------------------------------------------------
# 2. Missing values
# ------------------------------------------------------------

print("\n2. MISSING VALUES")
print("-" * 50)

print(complaints.isna().sum())


# ------------------------------------------------------------
# 3. Duplicate records
# ------------------------------------------------------------

print("\n3. DUPLICATE VALIDATION")
print("-" * 50)

print(
    "Exact duplicate rows:",
    complaints.duplicated().sum()
)


# ------------------------------------------------------------
# 4. Customer ID validation
# ------------------------------------------------------------

print("\n4. CUSTOMER ID VALIDATION")
print("-" * 50)

valid_customer_ids = set(
    tables["customers"]["customer_id"]
    .dropna()
    .astype(str)
)

invalid_customer_mask = ~(
    complaints["customer_id"]
    .astype(str)
    .isin(valid_customer_ids)
)

print(
    "Invalid customer IDs:",
    invalid_customer_mask.sum()
)


# ------------------------------------------------------------
# 5. Complaint status
# ------------------------------------------------------------

print("\n5. COMPLAINT STATUS")
print("-" * 50)

# Replace column name if your output shows a different name
print(
    complaints["status"]
    .value_counts(dropna=False)
)

COMPLAINTS DATA QUALITY INVESTIGATION

1. BASIC INFORMATION
--------------------------------------------------
Rows: 16584
Columns:
['complaint_id', 'customer_id', 'complaint_date', 'complaint_type', 'severity', 'status', 'resolution_date']

2. MISSING VALUES
--------------------------------------------------
complaint_id          0
customer_id           0
complaint_date        0
complaint_type        0
severity              0
status                0
resolution_date    7348
dtype: int64

3. DUPLICATE VALIDATION
--------------------------------------------------
Exact duplicate rows: 0

4. CUSTOMER ID VALIDATION
--------------------------------------------------
Invalid customer IDs: 0

5. COMPLAINT STATUS
--------------------------------------------------
status
Resolved      9236
Unresolved    7348
Name: count, dtype: int64


## Step 7G — Complaints Cleaning

The complaints investigation found no exact duplicate records and no invalid customer references. Complaint status contains only `Resolved` and `Unresolved` values. The 7,348 missing resolution dates correspond exactly to the 7,348 unresolved complaints, so these missing dates are considered valid and will be preserved.

The complaint and resolution dates will be converted to proper datetime format while legitimate complaint history is retained.



In [53]:
# ============================================================
# STEP 7G — COMPLAINTS CLEANING
# ============================================================

complaints_clean = tables["complaints"].copy()

print("COMPLAINTS CLEANING")
print("=" * 80)

# ------------------------------------------------------------
# 1. Remove exact duplicate rows
# ------------------------------------------------------------

before = len(complaints_clean)

complaints_clean = complaints_clean.drop_duplicates()

removed_duplicates = before - len(complaints_clean)

print(
    "Exact duplicate complaint rows removed:",
    removed_duplicates
)


# ------------------------------------------------------------
# 2. Parse dates
# ------------------------------------------------------------

complaints_clean["complaint_date"] = pd.to_datetime(
    complaints_clean["complaint_date"],
    format="mixed",
    errors="coerce"
)

complaints_clean["resolution_date"] = pd.to_datetime(
    complaints_clean["resolution_date"],
    format="mixed",
    errors="coerce"
)


# ------------------------------------------------------------
# 3. Final validation
# ------------------------------------------------------------

print("\nFINAL COMPLAINT VALIDATION")
print("=" * 80)

print("Rows:", len(complaints_clean))

print(
    "Unique complaint IDs:",
    complaints_clean["complaint_id"].nunique()
)

print(
    "Null customer IDs:",
    complaints_clean["customer_id"].isna().sum()
)

print(
    "Null resolution dates:",
    complaints_clean["resolution_date"].isna().sum()
)

print("\nComplaint Status:")
print(
    complaints_clean["status"]
    .value_counts(dropna=False)
)

COMPLAINTS CLEANING
Exact duplicate complaint rows removed: 0

FINAL COMPLAINT VALIDATION
Rows: 16584
Unique complaint IDs: 16584
Null customer IDs: 0
Null resolution dates: 7348

Complaint Status:
status
Resolved      9236
Unresolved    7348
Name: count, dtype: int64


In [54]:
# Save cleaned complaints data

complaints_clean.to_csv(
    "cleaned_data/complaints_clean.csv",
    index=False
)

print("Cleaned complaints data saved successfully.")
print("File: cleaned_data/complaints_clean.csv")
print("Rows:", len(complaints_clean))
print("Columns:", len(complaints_clean.columns))


Cleaned complaints data saved successfully.
File: cleaned_data/complaints_clean.csv
Rows: 16584
Columns: 7


## Step 7H — Customer Location Data Quality Investigation

The customer location fields will be investigated to validate state and circle information before using them for churn analysis. The investigation will check for missing values, invalid state references, inconsistent location values, and duplicate or invalid customer records.

The purpose is to ensure that state/circle-level churn analysis in Phase 2 is based on reliable location data.

**Cleaning principle:** Preserve valid customer records wherever possible. Only clearly invalid or inconsistent location values will be corrected or converted to null based on the investigation findings.


In [55]:
# ============================================================
# STEP 7H — CUSTOMER LOCATION DATA QUALITY INVESTIGATION
# ============================================================

customers_location = tables["customers"].copy()

print("CUSTOMER LOCATION DATA QUALITY INVESTIGATION")
print("=" * 90)


# ------------------------------------------------------------
# 1. Identify location columns
# ------------------------------------------------------------

print("\n1. CUSTOMER LOCATION COLUMNS")
print("-" * 50)

print(
    customers_location.columns.tolist()
)


# ------------------------------------------------------------
# 2. Missing values in location-related columns
# ------------------------------------------------------------

print("\n2. LOCATION MISSING VALUES")
print("-" * 50)

location_columns = [
    col for col in customers_location.columns
    if any(
        keyword in col.lower()
        for keyword in ["state", "city", "region", "circle", "pin"]
    )
]

print("Location-related columns:", location_columns)

print(
    customers_location[location_columns].isna().sum()
)

CUSTOMER LOCATION DATA QUALITY INVESTIGATION

1. CUSTOMER LOCATION COLUMNS
--------------------------------------------------
['customer_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'age', 'email', 'phone_number', 'address', 'city_id', 'city_name', 'state_id', 'pin_code', 'city_tier', 'region_id', 'occupation', 'annual_income_inr', 'customer_segment', 'product_line', 'plan_id', 'acquisition_channel', 'acquisition_date', 'tenure_months', 'customer_status', 'churn_date']

2. LOCATION MISSING VALUES
--------------------------------------------------
Location-related columns: ['city_id', 'city_name', 'state_id', 'pin_code', 'city_tier', 'region_id']
city_id      0
city_name    0
state_id     0
pin_code     0
city_tier    0
region_id    0
dtype: int64


In [56]:
# ------------------------------------------------------------
# 3. LOCATION ID VALIDATION
# ------------------------------------------------------------

print("\n3. LOCATION ID VALIDATION")
print("-" * 50)

# Valid city IDs from cities table
valid_city_ids = set(
    tables["cities"]["city_id"]
    .dropna()
    .astype(str)
)

# Valid state IDs from states table
valid_state_ids = set(
    tables["states"]["state_id"]
    .dropna()
    .astype(str)
)

# Valid region IDs from regions table
valid_region_ids = set(
    tables["regions"]["region_id"]
    .dropna()
    .astype(str)
)

invalid_city_mask = ~(
    customers_location["city_id"]
    .astype(str)
    .isin(valid_city_ids)
)

invalid_state_mask = ~(
    customers_location["state_id"]
    .astype(str)
    .isin(valid_state_ids)
)

invalid_region_mask = ~(
    customers_location["region_id"]
    .astype(str)
    .isin(valid_region_ids)
)

print(
    "Invalid city IDs:",
    invalid_city_mask.sum()
)

print(
    "Invalid state IDs:",
    invalid_state_mask.sum()
)

print(
    "Invalid region IDs:",
    invalid_region_mask.sum()
)


3. LOCATION ID VALIDATION
--------------------------------------------------
Invalid city IDs: 0
Invalid state IDs: 0
Invalid region IDs: 0


In [57]:
# ------------------------------------------------------------
# 4. LOCATION CONSISTENCY VALIDATION
# ------------------------------------------------------------

print("\n4. LOCATION CONSISTENCY VALIDATION")
print("-" * 50)

# ------------------------------------------------------------
# City → State consistency
# ------------------------------------------------------------

city_state_map = (
    tables["cities"]
    .set_index("city_id")["state_id"]
    .astype(str)
    .to_dict()
)

expected_state_ids = (
    customers_location["city_id"]
    .astype(str)
    .map(city_state_map)
)

city_state_mismatch = (
    expected_state_ids
    != customers_location["state_id"].astype(str)
)

print(
    "City-State mismatches:",
    city_state_mismatch.sum()
)





4. LOCATION CONSISTENCY VALIDATION
--------------------------------------------------
City-State mismatches: 0


In [58]:
# ------------------------------------------------------------
# CHECK STATES TABLE STRUCTURE
# ------------------------------------------------------------

print("STATES TABLE COLUMNS")
print("-" * 50)

print(tables["states"].columns.tolist())

print("\nStates sample:")
print(tables["states"].head())


STATES TABLE COLUMNS
--------------------------------------------------
['state_id', 'state_name', 'state_code', 'zone']

States sample:
  state_id     state_name state_code   zone
0    ST001          Delhi         DL  North
1    ST002        Haryana         HR  North
2    ST003         Punjab         PB  North
3    ST004  Uttar Pradesh         UP  North
4    ST005      Rajasthan         RJ  North


In [59]:
# ------------------------------------------------------------
# 5. CITIES TABLE STRUCTURE
# ------------------------------------------------------------

print("\n5. CITIES TABLE STRUCTURE")
print("-" * 50)

print("Cities table columns:")
print(tables["cities"].columns.tolist())

print("\nCities sample:")
print(tables["cities"].head())


5. CITIES TABLE STRUCTURE
--------------------------------------------------
Cities table columns:
['city_id', 'city_name', 'state_id', 'state_name', 'zone', 'region_id', 'tier', 'pin_prefix']

Cities sample:
  city_id  city_name state_id   state_name   zone region_id   tier  pin_prefix
0  CT0001  New Delhi    ST001        Delhi  North      RG01  Metro         110
1  CT0002     Mumbai    ST010  Maharashtra   West      RG02  Metro         400
2  CT0003  Bengaluru    ST015    Karnataka  South      RG03  Metro         560
3  CT0004    Chennai    ST016   Tamil Nadu  South      RG03  Metro         600
4  CT0005    Kolkata    ST022  West Bengal   East      RG04  Metro         700


In [60]:
# ------------------------------------------------------------
# 6. INVESTIGATE CITY NAME MISMATCHES
# ------------------------------------------------------------

print("\n6. CITY NAME MISMATCH INVESTIGATION")
print("-" * 50)

# Expected city names from cities lookup table
city_name_map = (
    tables["cities"]
    .set_index("city_id")["city_name"]
    .astype(str)
    .to_dict()
)

expected_city_names = (
    customers_location["city_id"]
    .astype(str)
    .map(city_name_map)
)

city_name_mismatch = (
    expected_city_names
    != customers_location["city_name"].astype(str)
)

# Show the mismatched values
city_mismatches = customers_location.loc[
    city_name_mismatch,
    ["customer_id", "city_id", "city_name"]
].copy()

city_mismatches["expected_city_name"] = expected_city_names[
    city_name_mismatch
].values

print("Total city name mismatches:", len(city_mismatches))

print("\nSample mismatches:")
print(
    city_mismatches.head(20).to_string(index=False)
)


6. CITY NAME MISMATCH INVESTIGATION
--------------------------------------------------
Total city name mismatches: 941

Sample mismatches:
customer_id city_id     city_name expected_city_name
   C0000013  CT0020      VADODARA           Vadodara
   C0000034  CT0006    Hyderaabad          Hyderabad
   C0000054  CT0008    Ahmedaabad          Ahmedabad
   C0000067  CT0006     HYDERABAD          Hyderabad
   C0000080  CT0065      SHILLONG           Shillong
   C0000085  CT0007          PUNE               Pune
   C0000094  CT0041     Belaagavi           Belagavi
   C0000098  CT0052      SILIGURI           Siliguri
   C0000139  CT0003     BENGALURU          Bengaluru
   C0000161  CT0036       Kaanpur             Kanpur
   C0000168  CT0001     NEW DELHI          New Delhi
   C0000194  CT0007         Punex               Pune
   C0000225  CT0033     Dehraadun           Dehradun
   C0000227  CT0067       Aizaawl             Aizawl
   C0000231  CT0041      BELAGAVI           Belagavi
   C0000234 

In [61]:
# ------------------------------------------------------------
# 7. CITY TIER CONSISTENCY VALIDATION
# ------------------------------------------------------------

print("\n7. CITY TIER CONSISTENCY VALIDATION")
print("-" * 50)

# Expected tier from cities lookup table
city_tier_map = (
    tables["cities"]
    .set_index("city_id")["tier"]
    .astype(str)
    .to_dict()
)

expected_city_tiers = (
    customers_location["city_id"]
    .astype(str)
    .map(city_tier_map)
)

city_tier_mismatch = (
    expected_city_tiers
    != customers_location["city_tier"].astype(str)
)

print(
    "City tier mismatches:",
    city_tier_mismatch.sum()
)


# ------------------------------------------------------------
# 8. PIN PREFIX CONSISTENCY
# ------------------------------------------------------------

print("\n8. PIN PREFIX CONSISTENCY")
print("-" * 50)

print(
    "Unique customer PIN prefixes:",
    customers_location["pin_code"]
    .astype(str)
    .str[:3]
    .nunique()
)

print(
    "Cities with PIN prefix reference:",
    tables["cities"]["pin_prefix"].notna().sum()
)


7. CITY TIER CONSISTENCY VALIDATION
--------------------------------------------------
City tier mismatches: 0

8. PIN PREFIX CONSISTENCY
--------------------------------------------------
Unique customer PIN prefixes: 233
Cities with PIN prefix reference: 68


## Step 7H — Customer Location Cleaning

The investigation found that all customer location IDs are valid and internally consistent. City-to-state and city-tier relationships also contain no mismatches.

A total of **941 customer city names** were found to differ from the authoritative `cities` reference table, primarily due to inconsistent capitalization and spelling variations. These city names will be standardized using the valid `city_id` as the lookup key.

No customer records will be deleted because of location inconsistencies.


In [62]:
# ============================================================
# STEP 7H — CUSTOMER LOCATION CLEANING
# ============================================================

customers_location_clean = tables["customers"].copy()

print("CUSTOMER LOCATION CLEANING")
print("=" * 80)


# ------------------------------------------------------------
# 1. Standardize city names using city_id
# ------------------------------------------------------------

city_name_map = (
    tables["cities"]
    .set_index("city_id")["city_name"]
    .astype(str)
    .to_dict()
)

expected_city_names = (
    customers_location_clean["city_id"]
    .astype(str)
    .map(city_name_map)
)

city_name_mismatch = (
    customers_location_clean["city_name"].astype(str)
    != expected_city_names
)

city_name_correction_count = city_name_mismatch.sum()

customers_location_clean.loc[
    city_name_mismatch,
    "city_name"
] = expected_city_names[city_name_mismatch]

print(
    "City names standardized:",
    city_name_correction_count
)


# ------------------------------------------------------------
# 2. Final validation
# ------------------------------------------------------------

print("\nFINAL CUSTOMER LOCATION VALIDATION")
print("=" * 80)

print(
    "Rows:",
    len(customers_location_clean)
)

print(
    "Unique customer IDs:",
    customers_location_clean["customer_id"].nunique()
)

print(
    "City name mismatches remaining:",
    (
        customers_location_clean["city_name"].astype(str)
        != customers_location_clean["city_id"]
        .astype(str)
        .map(city_name_map)
    ).sum()
)

print(
    "Null city IDs:",
    customers_location_clean["city_id"].isna().sum()
)

print(
    "Null state IDs:",
    customers_location_clean["state_id"].isna().sum()
)

print(
    "Null region IDs:",
    customers_location_clean["region_id"].isna().sum()
)

print(
    "Null city tiers:",
    customers_location_clean["city_tier"].isna().sum()
)

CUSTOMER LOCATION CLEANING
City names standardized: 941

FINAL CUSTOMER LOCATION VALIDATION
Rows: 19076
Unique customer IDs: 19000
City name mismatches remaining: 0
Null city IDs: 0
Null state IDs: 0
Null region IDs: 0
Null city tiers: 0


In [63]:
# ============================================================
# APPLY LOCATION CLEANING TO FINAL CUSTOMER DATA
# ============================================================

customers_clean["city_name"] = (
    customers_clean["city_id"]
    .astype(str)
    .map(city_name_map)
)

print("Location standardization applied to customers_clean.")
print("Rows:", len(customers_clean))
print("Unique customer IDs:", customers_clean["customer_id"].nunique())

Location standardization applied to customers_clean.
Rows: 19000
Unique customer IDs: 19000


In [64]:
# Final city-name validation

city_name_check = (
    customers_clean["city_name"].astype(str)
    == customers_clean["city_id"]
    .astype(str)
    .map(city_name_map)
)

print("City name mismatches remaining:", (~city_name_check).sum())

City name mismatches remaining: 0


In [65]:
# ============================================================
# SAVE UPDATED CUSTOMER CLEAN DATA
# ============================================================

customers_clean.to_csv(
    "cleaned_data/customers_clean.csv",
    index=False
)

print("Updated customers_clean.csv saved successfully.")
print("File: cleaned_data/customers_clean.csv")
print("Rows:", len(customers_clean))
print("Columns:", len(customers_clean.columns))

Updated customers_clean.csv saved successfully.
File: cleaned_data/customers_clean.csv
Rows: 19000
Columns: 25


----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
# NexaTel Customer Churn Analytics — Data Quality Report

**Phase:** Phase 1 — Data Cleaning & Quality Assessment
**Project:** NexaTel Customer Churn Analytics

## 1. Objective

The objective of Phase 1 was to assess the quality, consistency, completeness, uniqueness, and relational integrity of the NexaTel dataset before performing analysis and dashboard development.

The assessment covered the available source tables and included validation of **primary keys, foreign keys, missing values, duplicates, data types, date formats, categorical consistency, numeric validity, and known data-quality issues**.

## 2. Data Quality Validation Performed

The following validations were completed:

* **Primary Key Validation:** Checked uniqueness and duplicate records across relevant tables.
* **Foreign Key Validation:** Verified relationships between related tables and identified orphan/unmatched references.
* **Missing Value Validation:** Identified null/blank values in important fields.
* **Duplicate Record Validation:** Identified duplicate customer and transactional records.
* **Data Type Validation:** Reviewed columns for appropriate data types.
* **Date Validation:** Checked date fields for inconsistent or mixed formats.
* **Categorical Consistency:** Checked spelling, capitalization, and inconsistent category values.
* **Numeric Validation:** Checked for negative, impossible, or otherwise invalid numeric values.
* **Business Rule Validation:** Investigated values that appeared unusual or potentially erroneous.
* **Data Quality Issue Log Review:** Cross-checked detected issues against the supplied `data_quality_issue_log.csv`.

## 3. Key Findings

| Area          | Finding                                                                               | Action/Status                          |
| ------------- | ------------------------------------------------------------------------------------- | -------------------------------------- |
| Customer IDs  | 19,076 customer records with 19,000 unique customer IDs; **76 duplicates** identified | Flagged                                |
| Billing IDs   | 115,313 records with 114,969 unique invoice IDs; **344 duplicates** identified        | Flagged                                |
| Customer Data | Missing email, address and income values identified                                   | Flagged                                |
| Customer Data | Invalid phone/email, incorrect PIN and impossible age values identified               | Flagged                                |
| Customer Data | Misspelled city and inconsistent capitalization identified                            | Flagged                                |
| Dates         | Mixed date formats identified in affected records                                     | Flagged                                |
| Billing       | Incorrect GST values and negative invoice amounts identified                          | Flagged                                |
| Relationships | Primary-key and foreign-key integrity validations completed                           | Validated                              |
| Usage Data    | High-usage records investigated using multiple thresholds                             | Investigated/Flagged where appropriate |

## 4. Important Data Quality Issues Identified

The supplied quality log confirms several known issues, including:

* **760** missing customer emails
* **380** missing customer addresses
* **950** missing customer income values
* **228** invalid phone numbers
* **285** invalid email addresses
* **190** incorrect PIN values
* **380** misspelled city values
* **570** inconsistent capitalization records
* **38** impossible-age records
* **380** mixed-date-format records
* **76** duplicate customer records
* **1,149** incorrect GST records in billing
* **229** negative invoice-amount records

## 5. Data Quality Decision

The dataset is **usable for further analysis**, but identified quality issues must be handled appropriately during the subsequent analysis stages.

The issues have **not been blindly deleted or overwritten**. Records requiring correction, exclusion, or interpretation have been **flagged**, with business context considered before transformation.

### Phase 1 Status: ✅ COMPLETED

**All required Phase 1 data-quality validations have been completed.**

**Primary-key validation:** Completed
**Foreign-key validation:** Completed
**Missing-value validation:** Completed
**Duplicate validation:** Completed
**Data-type validation:** Completed
**Date validation:** Completed
**Categorical consistency validation:** Completed
**Numeric/business-rule validation:** Completed
**Data-quality issues:** Identified and flagged

**Conclusion:** The NexaTel dataset is sufficiently assessed and ready to proceed to the next phase of the Customer Churn Analytics project.
